local M = {}

-- NOTE: When adding new icons, remember to add an entry to the `filetypes` table, if applicable.
local icons, icons_by_filename, icons_by_file_extension, icons_by_operating_system
local icons_by_desktop_environment, icons_by_window_manager

local default_icon = {
    icon = "",
    color = "#6d8086",
    cterm_color = "66",
    name = "Default",
}

function M.get_icons()
    return icons
end

function M.get_icons_by_filename()
    return icons_by_filename
end

function M.get_icons_by_extension()
    return icons_by_file_extension
end

function M.get_icons_by_operating_system()
    return icons_by_operating_system
end

function M.get_icons_by_desktop_environment()
    return icons_by_desktop_environment
end

function M.get_icons_by_window_manager()
    return icons_by_window_manager
end

local global_opts = {
    override = {},
    strict = false,
    default = false,
    color_icons = true,
}

-- Set the current icons tables, depending on the 'background' option.
local function refresh_icons()
    local theme
    if vim.o.background == "light" then
        theme = require("nvim-web-devicons.icons-light")
    else
        theme = require("nvim-web-devicons.icons-default")
    end

    icons_by_filename = theme.icons_by_filename
    icons_by_file_extension = theme.icons_by_file_extension
    icons_by_operating_system = theme.icons_by_operating_system
    icons_by_desktop_environment = theme.icons_by_desktop_environment
    icons_by_window_manager = theme.icons_by_window_manager
    icons = vim.tbl_extend(
        "keep",
        {},
        icons_by_filename,
        icons_by_file_extension,
        icons_by_operating_system,
        icons_by_desktop_environment,
        icons_by_window_manager
    )
    icons = vim.tbl_extend("force", icons, global_opts.override)
    icons[1] = default_icon
end

-- Map of filetypes -> icon names
local filetypes = {
    ["stl"] = "stl",
    ["stp"] = "stp",
    ["obj"] = "obj",
    ["o"] = "o",
    ["ac"] = "ac",
    ["dxf"] = "dxf",
    ["fbx"] = "fbx",
    ["mesh"] = "mesh",
    ["mqo"] = "mqo",
    ["pmd"] = "pmd",
    ["pmx"] = "pmx",
    ["skp"] = "skp",
    ["vac"] = "vac",
    ["vdp"] = "vdp",
    ["vox"] = "vox",
    ["blend"] = "blend",
    ["abc"] = "abc",
    ["accdb"] = "accdb",
    ["accdt"] = "accdt",
    ["mdb"] = "mdb",
    ["accda"] = "accda",
    ["accdc"] = "accdc",
    ["accde"] = "accde",
    ["accdp"] = "accdp",
    ["accdr"] = "accdr",
    ["accdu"] = "accdu",
    ["ade"] = "ade",
    ["adp"] = "adp",
    ["laccdb"] = "laccdb",
    ["ldb"] = "ldb",
    ["mam"] = "mam",
    ["maq"] = "maq",
    ["mdw"] = "mdw",
    ["ada"] = "ada",
    ["adb"] = "adb",
    ["ads"] = "ads",
    ["ali"] = "ali",
    ["apk"] = "apk",
    ["smali"] = "smali",
    ["dex"] = "dex",
    ["component.ts"] = "component.ts",
    ["component.js"] = "component.js",
    ["directive.ts"] = "directive.ts",
    ["directive.js"] = "directive.js",
    ["guard.ts"] = "guard.ts",
    ["guard.js"] = "guard.js",
    ["pipe.ts"] = "pipe.ts",
    ["pipe.js"] = "pipe.js",
    ["resolver.ts"] = "resolver.ts",
    ["resolver.js"] = "resolver.js",
    ["service.ts"] = "service.ts",
    ["service.js"] = "service.js",
    ["module.ts"] = "module.ts",
    ["module.js"] = "module.js",
    ["ng-template"] = "ng-template",
    ["g4"] = "g4",
    ["age"] = "age",
    ["apacheconf"] = "apacheconf",
    ["applescript"] = "applescript",
    ["ipa"] = "ipa",
    [".DS_Store"] = ".DS_Store",
    ["architecture.md"] = "architecture.md",
    ["architecture.rst"] = "architecture.rst",
    ["architecture.txt"] = "architecture.txt",
    ["architecture"] = "architecture",
    ["ino"] = "ino",
    ["asm"] = "asm",
    ["a51"] = "a51",
    ["inc"] = "inc",
    ["nasm"] = "nasm",
    ["s"] = "s",
    ["ms"] = "ms",
    ["agc"] = "agc",
    ["ags"] = "ags",
    ["aea"] = "aea",
    ["argus"] = "argus",
    ["mitigus"] = "mitigus",
    ["binsource"] = "binsource",
    ["astro"] = "astro",
    ["astro.config.js"] = "astro.config.js",
    ["astro.config.mjs"] = "astro.config.mjs",
    ["astro.config.cjs"] = "astro.config.cjs",
    ["astro.config.ts"] = "astro.config.ts",
    ["astro.config.cts"] = "astro.config.cts",
    ["astro.config.mts"] = "astro.config.mts",
    [".astylerc"] = ".astylerc",
    ["mp3"] = "mp3",
    ["flac"] = "flac",
    ["m4a"] = "m4a",
    ["wma"] = "wma",
    ["aiff"] = "aiff",
    ["wav"] = "wav",
    ["authors.md"] = "authors.md",
    ["authors.rst"] = "authors.rst",
    ["authors.txt"] = "authors.txt",
    ["authors"] = "authors",
    ["contributors.md"] = "contributors.md",
    ["contributors.rst"] = "contributors.rst",
    ["contributors.txt"] = "contributors.txt",
    ["contributors"] = "contributors",
    [".autorc"] = ".autorc",
    ["auto.config.js"] = "auto.config.js",
    ["auto.config.ts"] = "auto.config.ts",
    ["auto-config.json"] = "auto-config.json",
    ["auto-config.yaml"] = "auto-config.yaml",
    ["auto-config.yml"] = "auto-config.yml",
    ["auto-config.ts"] = "auto-config.ts",
    ["auto-config.js"] = "auto-config.js",
    ["ahk"] = "ahk",
    ["azure-pipelines.yml"] = "azure-pipelines.yml",
    ["azure-pipelines.yaml"] = "azure-pipelines.yaml",
    ["azure-pipelines-main.yml"] = "azure-pipelines-main.yml",
    ["azure-pipelines-main.yaml"] = "azure-pipelines-main.yaml",
    ["azcli"] = "azcli",
    [".babelrc"] = ".babelrc",
    [".babelrc.json"] = ".babelrc.json",
    [".babelrc.jsonc"] = ".babelrc.jsonc",
    [".babelrc.json5"] = ".babelrc.json5",
    [".babelrc.yaml"] = ".babelrc.yaml",
    [".babelrc.yml"] = ".babelrc.yml",
    [".babelrc.toml"] = ".babelrc.toml",
    [".babelrc.js"] = ".babelrc.js",
    [".babelrc.mjs"] = ".babelrc.mjs",
    [".babelrc.cjs"] = ".babelrc.cjs",
    [".babelrc.ts"] = ".babelrc.ts",
    [".babelrc.mts"] = ".babelrc.mts",
    [".babelrc.cts"] = ".babelrc.cts",
    ["babel.config.json"] = "babel.config.json",
    ["babel.config.jsonc"] = "babel.config.jsonc",
    ["babel.config.json5"] = "babel.config.json5",
    ["babel.config.yaml"] = "babel.config.yaml",
    ["babel.config.yml"] = "babel.config.yml",
    ["babel.config.toml"] = "babel.config.toml",
    ["babel.config.js"] = "babel.config.js",
    ["babel.config.mjs"] = "babel.config.mjs",
    ["babel.config.cjs"] = "babel.config.cjs",
    ["babel.config.ts"] = "babel.config.ts",
    ["babel.config.mts"] = "babel.config.mts",
    ["babel.config.cts"] = "babel.config.cts",
    [".babel-plugin-macrosrc"] = ".babel-plugin-macrosrc",
    [".babel-plugin-macrosrc.json"] = ".babel-plugin-macrosrc.json",
    [".babel-plugin-macrosrc.jsonc"] = ".babel-plugin-macrosrc.jsonc",
    [".babel-plugin-macrosrc.json5"] = ".babel-plugin-macrosrc.json5",
    [".babel-plugin-macrosrc.yaml"] = ".babel-plugin-macrosrc.yaml",
    [".babel-plugin-macrosrc.yml"] = ".babel-plugin-macrosrc.yml",
    [".babel-plugin-macrosrc.toml"] = ".babel-plugin-macrosrc.toml",
    [".babel-plugin-macrosrc.js"] = ".babel-plugin-macrosrc.js",
    [".babel-plugin-macrosrc.mjs"] = ".babel-plugin-macrosrc.mjs",
    [".babel-plugin-macrosrc.cjs"] = ".babel-plugin-macrosrc.cjs",
    [".babel-plugin-macrosrc.ts"] = ".babel-plugin-macrosrc.ts",
    [".babel-plugin-macrosrc.mts"] = ".babel-plugin-macrosrc.mts",
    [".babel-plugin-macrosrc.cts"] = ".babel-plugin-macrosrc.cts",
    ["babel-plugin-macros.config.json"] = "babel-plugin-macros.config.json",
    ["babel-plugin-macros.config.jsonc"] = "babel-plugin-macros.config.jsonc",
    ["babel-plugin-macros.config.json5"] = "babel-plugin-macros.config.json5",
    ["babel-plugin-macros.config.yaml"] = "babel-plugin-macros.config.yaml",
    ["babel-plugin-macros.config.yml"] = "babel-plugin-macros.config.yml",
    ["babel-plugin-macros.config.toml"] = "babel-plugin-macros.config.toml",
    ["babel-plugin-macros.config.js"] = "babel-plugin-macros.config.js",
    ["babel-plugin-macros.config.mjs"] = "babel-plugin-macros.config.mjs",
    ["babel-plugin-macros.config.cjs"] = "babel-plugin-macros.config.cjs",
    ["babel-plugin-macros.config.ts"] = "babel-plugin-macros.config.ts",
    ["babel-plugin-macros.config.mts"] = "babel-plugin-macros.config.mts",
    ["babel-plugin-macros.config.cts"] = "babel-plugin-macros.config.cts",
    ["babel-transform.js"] = "babel-transform.js",
    ["bats"] = "bats",
    ["bzl"] = "bzl",
    ["bazel"] = "bazel",
    [".bazelignore"] = ".bazelignore",
    [".bazelrc"] = ".bazelrc",
    [".bazelversion"] = ".bazelversion",
    ["bicep"] = "bicep",
    ["bitbucket-pipelines.yaml"] = "bitbucket-pipelines.yaml",
    ["bitbucket-pipelines.yml"] = "bitbucket-pipelines.yml",
    [".bowerrc"] = ".bowerrc",
    ["bower.json"] = "bower.json",
    ["b"] = "b",
    ["bf"] = "bf",
    ["c"] = "c",
    ["i"] = "i",
    ["mi"] = "mi",
    ["cake"] = "cake",
    ["Cargo.toml"] = "Cargo.toml",
    ["cer"] = "cer",
    ["cert"] = "cert",
    ["crt"] = "crt",
    ["copying"] = "copying",
    ["copying.md"] = "copying.md",
    ["copying.rst"] = "copying.rst",
    ["copying.txt"] = "copying.txt",
    ["copyright"] = "copyright",
    ["copyright.md"] = "copyright.md",
    ["copyright.rst"] = "copyright.rst",
    ["copyright.txt"] = "copyright.txt",
    ["license-agpl"] = "license-agpl",
    ["license-apache"] = "license-apache",
    ["license-bsd"] = "license-bsd",
    ["license-mit"] = "license-mit",
    ["license-gpl"] = "license-gpl",
    ["license-lgpl"] = "license-lgpl",
    ["license.md"] = "license.md",
    ["license.rst"] = "license.rst",
    ["license.txt"] = "license.txt",
    ["LICENSE"] = "LICENSE",
    ["changelog"] = "changelog",
    ["changelog.md"] = "changelog.md",
    ["changelog.rst"] = "changelog.rst",
    ["changelog.txt"] = "changelog.txt",
    ["changes"] = "changes",
    ["changes.md"] = "changes.md",
    ["changes.rst"] = "changes.rst",
    ["changes.txt"] = "changes.txt",
    ["pgn"] = "pgn",
    ["fen"] = "fen",
    ["crx"] = "crx",
    ["clj"] = "clj",
    ["cljs"] = "cljs",
    ["cljc"] = "cljc",
    ["codeowners"] = "codeowners",
    ["OWNERS"] = "OWNERS",
    ["coffeelint.json"] = "coffeelint.json",
    [".coffeelintignore"] = ".coffeelintignore",
    ["coffee"] = "coffee",
    ["cson"] = "cson",
    ["iced"] = "iced",
    ["cfml"] = "cfml",
    ["cfc"] = "cfc",
    ["lucee"] = "lucee",
    ["cfm"] = "cfm",
    ["command"] = "command",
    [".commitlintrc"] = ".commitlintrc",
    [".commitlintrc.json"] = ".commitlintrc.json",
    [".commitlintrc.jsonc"] = ".commitlintrc.jsonc",
    [".commitlintrc.json5"] = ".commitlintrc.json5",
    [".commitlintrc.yaml"] = ".commitlintrc.yaml",
    [".commitlintrc.yml"] = ".commitlintrc.yml",
    [".commitlintrc.toml"] = ".commitlintrc.toml",
    [".commitlintrc.js"] = ".commitlintrc.js",
    [".commitlintrc.mjs"] = ".commitlintrc.mjs",
    [".commitlintrc.cjs"] = ".commitlintrc.cjs",
    [".commitlintrc.ts"] = ".commitlintrc.ts",
    [".commitlintrc.mts"] = ".commitlintrc.mts",
    [".commitlintrc.cts"] = ".commitlintrc.cts",
    ["commitlint.config.json"] = "commitlint.config.json",
    ["commitlint.config.jsonc"] = "commitlint.config.jsonc",
    ["commitlint.config.json5"] = "commitlint.config.json5",
    ["commitlint.config.yaml"] = "commitlint.config.yaml",
    ["commitlint.config.yml"] = "commitlint.config.yml",
    ["commitlint.config.toml"] = "commitlint.config.toml",
    ["commitlint.config.js"] = "commitlint.config.js",
    ["commitlint.config.mjs"] = "commitlint.config.mjs",
    ["commitlint.config.cjs"] = "commitlint.config.cjs",
    ["commitlint.config.ts"] = "commitlint.config.ts",
    ["commitlint.config.mts"] = "commitlint.config.mts",
    ["commitlint.config.cts"] = "commitlint.config.cts",
    [".commitlint.yaml"] = ".commitlint.yaml",
    [".commitlint.yml"] = ".commitlint.yml",
    ["code_of_conduct.md"] = "code_of_conduct.md",
    ["code_of_conduct.txt"] = "code_of_conduct.txt",
    ["code_of_conduct"] = "code_of_conduct",
    ["sh"] = "sh",
    ["ksh"] = "ksh",
    ["csh"] = "csh",
    ["tcsh"] = "tcsh",
    ["zsh"] = "zsh",
    ["bat"] = "bat",
    ["awk"] = "awk",
    ["exp"] = "exp",
    ["nu"] = "nu",
    ["bash"] = "bash",
    ["cmd"] = "cmd",
    ["fish"] = "fish",
    ["contributing.md"] = "contributing.md",
    ["contributing.rst"] = "contributing.rst",
    ["contributing.txt"] = "contributing.txt",
    ["contributing"] = "contributing",
    ["confluence"] = "confluence",
    [".coveralls.yml"] = ".coveralls.yml",
    ["cc"] = "cc",
    ["cpp"] = "cpp",
    ["cxx"] = "cxx",
    ["c++"] = "c++",
    ["cp"] = "cp",
    ["mii"] = "mii",
    ["ii"] = "ii",
    ["credits.md"] = "credits.md",
    ["credits.rst"] = "credits.rst",
    ["credits.txt"] = "credits.txt",
    ["credits"] = "credits",
    ["cr"] = "cr",
    ["ecr"] = "ecr",
    ["cs"] = "cs",
    ["csx"] = "csx",
    ["csharp"] = "csharp",
    ["css.map"] = "css.map",
    ["css"] = "css",
    ["d"] = "d",
    ["freezed.dart"] = "freezed.dart",
    ["g.dart"] = "g.dart",
    ["dart"] = "dart",
    ["pdb"] = "pdb",
    ["sql"] = "sql",
    ["pks"] = "pks",
    ["pkb"] = "pkb",
    ["sqlite"] = "sqlite",
    ["sqlite3"] = "sqlite3",
    ["pgsql"] = "pgsql",
    ["postgres"] = "postgres",
    ["plpgsql"] = "plpgsql",
    ["psql"] = "psql",
    ["db"] = "db",
    ["db3"] = "db3",
    ["dblite"] = "dblite",
    ["dblite3"] = "dblite3",
    ["debugsymbols"] = "debugsymbols",
    ["dsc"] = "dsc",
    ["deb"] = "deb",
    ["dependabot.yml"] = "dependabot.yml",
    ["dependabot.yaml"] = "dependabot.yaml",
    ["dhall"] = "dhall",
    ["dhallb"] = "dhallb",
    ["diff"] = "diff",
    ["iso"] = "iso",
    ["vmdk"] = "vmdk",
    ["hdd"] = "hdd",
    ["qcow"] = "qcow",
    ["qcow2"] = "qcow2",
    ["qed"] = "qed",
    ["dmg"] = "dmg",
    ["djt"] = "djt",
    ["django-html"] = "django-html",
    ["django-txt"] = "django-txt",
    ["dll"] = "dll",
    ["ilk"] = "ilk",
    ["so"] = "so",
    ["dockerfile"] = "dockerfile",
    ["dockerfile.prod"] = "dockerfile.prod",
    ["dockerfile.production"] = "dockerfile.production",
    ["dockerfile.alpha"] = "dockerfile.alpha",
    ["dockerfile.beta"] = "dockerfile.beta",
    ["dockerfile.stage"] = "dockerfile.stage",
    ["dockerfile.staging"] = "dockerfile.staging",
    ["dockerfile.dev"] = "dockerfile.dev",
    ["dockerfile.development"] = "dockerfile.development",
    ["dockerfile.local"] = "dockerfile.local",
    ["dockerfile.test"] = "dockerfile.test",
    ["dockerfile.testing"] = "dockerfile.testing",
    ["dockerfile.ci"] = "dockerfile.ci",
    ["dockerfile.web"] = "dockerfile.web",
    ["dockerfile.worker"] = "dockerfile.worker",
    ["docker-compose.yml"] = "docker-compose.yml",
    ["docker-compose.override.yml"] = "docker-compose.override.yml",
    ["docker-compose.prod.yml"] = "docker-compose.prod.yml",
    ["docker-compose.production.yml"] = "docker-compose.production.yml",
    ["docker-compose.alpha.yml"] = "docker-compose.alpha.yml",
    ["docker-compose.beta.yml"] = "docker-compose.beta.yml",
    ["docker-compose.stage.yml"] = "docker-compose.stage.yml",
    ["docker-compose.staging.yml"] = "docker-compose.staging.yml",
    ["docker-compose.dev.yml"] = "docker-compose.dev.yml",
    ["docker-compose.development.yml"] = "docker-compose.development.yml",
    ["docker-compose.local.yml"] = "docker-compose.local.yml",
    ["docker-compose.test.yml"] = "docker-compose.test.yml",
    ["docker-compose.testing.yml"] = "docker-compose.testing.yml",
    ["docker-compose.ci.yml"] = "docker-compose.ci.yml",
    ["docker-compose.web.yml"] = "docker-compose.web.yml",
    ["docker-compose.worker.yml"] = "docker-compose.worker.yml",
    ["docker-compose.yaml"] = "docker-compose.yaml",
    ["docker-compose.override.yaml"] = "docker-compose.override.yaml",
    ["docker-compose.prod.yaml"] = "docker-compose.prod.yaml",
    ["docker-compose.production.yaml"] = "docker-compose.production.yaml",
    ["docker-compose.alpha.yaml"] = "docker-compose.alpha.yaml",
    ["docker-compose.beta.yaml"] = "docker-compose.beta.yaml",
    ["docker-compose.stage.yaml"] = "docker-compose.stage.yaml",
    ["docker-compose.staging.yaml"] = "docker-compose.staging.yaml",
    ["docker-compose.dev.yaml"] = "docker-compose.dev.yaml",
    ["docker-compose.development.yaml"] = "docker-compose.development.yaml",
    ["docker-compose.local.yaml"] = "docker-compose.local.yaml",
    ["docker-compose.test.yaml"] = "docker-compose.test.yaml",
    ["docker-compose.testing.yaml"] = "docker-compose.testing.yaml",
    ["docker-compose.ci.yaml"] = "docker-compose.ci.yaml",
    ["docker-compose.web.yaml"] = "docker-compose.web.yaml",
    ["docker-compose.worker.yaml"] = "docker-compose.worker.yaml",
    ["containerfile"] = "containerfile",
    ["containerfile.prod"] = "containerfile.prod",
    ["containerfile.production"] = "containerfile.production",
    ["containerfile.alpha"] = "containerfile.alpha",
    ["containerfile.beta"] = "containerfile.beta",
    ["containerfile.stage"] = "containerfile.stage",
    ["containerfile.staging"] = "containerfile.staging",
    ["containerfile.dev"] = "containerfile.dev",
    ["containerfile.development"] = "containerfile.development",
    ["containerfile.local"] = "containerfile.local",
    ["containerfile.test"] = "containerfile.test",
    ["containerfile.testing"] = "containerfile.testing",
    ["containerfile.ci"] = "containerfile.ci",
    ["containerfile.web"] = "containerfile.web",
    ["containerfile.worker"] = "containerfile.worker",
    ["compose.yaml"] = "compose.yaml",
    ["compose.override.yaml"] = "compose.override.yaml",
    ["compose.prod.yaml"] = "compose.prod.yaml",
    ["compose.production.yaml"] = "compose.production.yaml",
    ["compose.alpha.yaml"] = "compose.alpha.yaml",
    ["compose.beta.yaml"] = "compose.beta.yaml",
    ["compose.stage.yaml"] = "compose.stage.yaml",
    ["compose.staging.yaml"] = "compose.staging.yaml",
    ["compose.dev.yaml"] = "compose.dev.yaml",
    ["compose.development.yaml"] = "compose.development.yaml",
    ["compose.local.yaml"] = "compose.local.yaml",
    ["compose.test.yaml"] = "compose.test.yaml",
    ["compose.testing.yaml"] = "compose.testing.yaml",
    ["compose.ci.yaml"] = "compose.ci.yaml",
    ["compose.web.yaml"] = "compose.web.yaml",
    ["compose.worker.yaml"] = "compose.worker.yaml",
    ["compose.yml"] = "compose.yml",
    ["compose.override.yml"] = "compose.override.yml",
    ["compose.prod.yml"] = "compose.prod.yml",
    ["compose.production.yml"] = "compose.production.yml",
    ["compose.alpha.yml"] = "compose.alpha.yml",
    ["compose.beta.yml"] = "compose.beta.yml",
    ["compose.stage.yml"] = "compose.stage.yml",
    ["compose.staging.yml"] = "compose.staging.yml",
    ["compose.dev.yml"] = "compose.dev.yml",
    ["compose.development.yml"] = "compose.development.yml",
    ["compose.local.yml"] = "compose.local.yml",
    ["compose.test.yml"] = "compose.test.yml",
    ["compose.testing.yml"] = "compose.testing.yml",
    ["compose.ci.yml"] = "compose.ci.yml",
    ["compose.web.yml"] = "compose.web.yml",
    ["compose.worker.yml"] = "compose.worker.yml",
    ["txt"] = "txt",
    ["drone.yml"] = "drone.yml",
    ["edge"] = "edge",
    [".editorconfig"] = ".editorconfig",
    ["ex"] = "ex",
    ["exs"] = "exs",
    ["eex"] = "eex",
    ["leex"] = "leex",
    ["heex"] = "heex",
    ["elm"] = "elm",
    ["ics"] = "ics",
    [".mailmap"] = ".mailmap",
    ["el"] = "el",
    ["elc"] = "elc",
    [".ember-cli"] = ".ember-cli",
    [".ember-cli.js"] = ".ember-cli.js",
    ["ember-cli-builds.js"] = "ember-cli-builds.js",
    ["erl"] = "erl",
    [".eslintrc"] = ".eslintrc",
    [".eslintrc.json"] = ".eslintrc.json",
    [".eslintrc.jsonc"] = ".eslintrc.jsonc",
    [".eslintrc.json5"] = ".eslintrc.json5",
    [".eslintrc.yaml"] = ".eslintrc.yaml",
    [".eslintrc.yml"] = ".eslintrc.yml",
    [".eslintrc.toml"] = ".eslintrc.toml",
    [".eslintrc.js"] = ".eslintrc.js",
    [".eslintrc.mjs"] = ".eslintrc.mjs",
    [".eslintrc.cjs"] = ".eslintrc.cjs",
    [".eslintrc.ts"] = ".eslintrc.ts",
    [".eslintrc.mts"] = ".eslintrc.mts",
    [".eslintrc.cts"] = ".eslintrc.cts",
    ["eslint.config.json"] = "eslint.config.json",
    ["eslint.config.jsonc"] = "eslint.config.jsonc",
    ["eslint.config.json5"] = "eslint.config.json5",
    ["eslint.config.yaml"] = "eslint.config.yaml",
    ["eslint.config.yml"] = "eslint.config.yml",
    ["eslint.config.toml"] = "eslint.config.toml",
    ["eslint.config.js"] = "eslint.config.js",
    ["eslint.config.mjs"] = "eslint.config.mjs",
    ["eslint.config.cjs"] = "eslint.config.cjs",
    ["eslint.config.ts"] = "eslint.config.ts",
    ["eslint.config.mts"] = "eslint.config.mts",
    ["eslint.config.cts"] = "eslint.config.cts",
    [".eslintrc-md.js"] = ".eslintrc-md.js",
    [".eslintrc-jsdoc.js"] = ".eslintrc-jsdoc.js",
    [".eslintignore"] = ".eslintignore",
    [".eslintcache"] = ".eslintcache",
    [".eslintrc.base.json"] = ".eslintrc.base.json",
    ["exe"] = "exe",
    ["msi"] = "msi",
    ["favicon.ico"] = "favicon.ico",
    ["fig"] = "fig",
    ["firebase.json"] = "firebase.json",
    [".firebaserc"] = ".firebaserc",
    ["firestore.rules"] = "firestore.rules",
    ["firestore.indexes.json"] = "firestore.indexes.json",
    ["woff"] = "woff",
    ["woff2"] = "woff2",
    ["ttf"] = "ttf",
    ["eot"] = "eot",
    ["suit"] = "suit",
    ["otf"] = "otf",
    ["bmap"] = "bmap",
    ["fnt"] = "fnt",
    ["odttf"] = "odttf",
    ["ttc"] = "ttc",
    ["font"] = "font",
    ["fonts"] = "fonts",
    ["sui"] = "sui",
    ["ntf"] = "ntf",
    ["mrf"] = "mrf",
    ["f"] = "f",
    ["f77"] = "f77",
    ["f90"] = "f90",
    ["f95"] = "f95",
    ["f03"] = "f03",
    ["f08"] = "f08",
    ["fs"] = "fs",
    ["fsx"] = "fsx",
    ["fsi"] = "fsi",
    ["fsproj"] = "fsproj",
    ["funding.yml"] = "funding.yml",
    ["gatsby-config.js"] = "gatsby-config.js",
    ["gatsby-config.mjs"] = "gatsby-config.mjs",
    ["gatsby-config.ts"] = "gatsby-config.ts",
    ["gatsby-node.js"] = "gatsby-node.js",
    ["gatsby-node.mjs"] = "gatsby-node.mjs",
    ["gatsby-node.ts"] = "gatsby-node.ts",
    ["gatsby-browser.js"] = "gatsby-browser.js",
    ["gatsby-browser.tsx"] = "gatsby-browser.tsx",
    ["gatsby-ssr.js"] = "gatsby-ssr.js",
    ["gatsby-ssr.tsx"] = "gatsby-ssr.tsx",
    [".gcloudignore"] = ".gcloudignore",
    ["Gemfile"] = "Gemfile",
    ["gmi"] = "gmi",
    ["gemini"] = "gemini",
    [".git"] = ".git",
    [".gitignore"] = ".gitignore",
    [".gitmessage"] = ".gitmessage",
    [".gitignore-global"] = ".gitignore-global",
    [".gitignore_global"] = ".gitignore_global",
    [".gitattributes"] = ".gitattributes",
    [".gitattributes-global"] = ".gitattributes-global",
    [".gitattributes_global"] = ".gitattributes_global",
    [".gitconfig"] = ".gitconfig",
    [".gitmodules"] = ".gitmodules",
    [".gitkeep"] = ".gitkeep",
    [".keep"] = ".keep",
    [".gitpreserve"] = ".gitpreserve",
    [".gitinclude"] = ".gitinclude",
    [".git-blame-ignore"] = ".git-blame-ignore",
    [".git-blame-ignore-revs"] = ".git-blame-ignore-revs",
    [".git-for-windows-updater"] = ".git-for-windows-updater",
    ["git-history"] = "git-history",
    ["gitlab-ci.yml"] = "gitlab-ci.yml",
    ["go.mod"] = "go.mod",
    ["go.sum"] = "go.sum",
    ["go.work"] = "go.work",
    ["go.work.sum"] = "go.work.sum",
    ["go"] = "go",
    ["godot"] = "godot",
    ["tres"] = "tres",
    ["tscn"] = "tscn",
    ["gdns"] = "gdns",
    ["gdnlib"] = "gdnlib",
    ["gdshader"] = "gdshader",
    ["gdshaderinc"] = "gdshaderinc",
    ["gdextension"] = "gdextension",
    [".gdignore"] = ".gdignore",
    ["._sc_"] = "._sc_",
    ["_sc_"] = "_sc_",
    ["gd"] = "gd",
    ["gradle"] = "gradle",
    ["gradle.properties"] = "gradle.properties",
    ["gradlew"] = "gradlew",
    ["gradle-wrapper.properties"] = "gradle-wrapper.properties",
    ["graphql"] = "graphql",
    ["gql"] = "gql",
    [".graphqlrc"] = ".graphqlrc",
    [".graphqlrc.json"] = ".graphqlrc.json",
    [".graphqlrc.jsonc"] = ".graphqlrc.jsonc",
    [".graphqlrc.json5"] = ".graphqlrc.json5",
    [".graphqlrc.yaml"] = ".graphqlrc.yaml",
    [".graphqlrc.yml"] = ".graphqlrc.yml",
    [".graphqlrc.toml"] = ".graphqlrc.toml",
    [".graphqlrc.js"] = ".graphqlrc.js",
    [".graphqlrc.mjs"] = ".graphqlrc.mjs",
    [".graphqlrc.cjs"] = ".graphqlrc.cjs",
    [".graphqlrc.ts"] = ".graphqlrc.ts",
    [".graphqlrc.mts"] = ".graphqlrc.mts",
    [".graphqlrc.cts"] = ".graphqlrc.cts",
    ["graphql.config.json"] = "graphql.config.json",
    ["graphql.config.jsonc"] = "graphql.config.jsonc",
    ["graphql.config.json5"] = "graphql.config.json5",
    ["graphql.config.yaml"] = "graphql.config.yaml",
    ["graphql.config.yml"] = "graphql.config.yml",
    ["graphql.config.toml"] = "graphql.config.toml",
    ["graphql.config.js"] = "graphql.config.js",
    ["graphql.config.mjs"] = "graphql.config.mjs",
    ["graphql.config.cjs"] = "graphql.config.cjs",
    ["graphql.config.ts"] = "graphql.config.ts",
    ["graphql.config.mts"] = "graphql.config.mts",
    ["graphql.config.cts"] = "graphql.config.cts",
    [".graphqlconfig"] = ".graphqlconfig",
    ["gulpfile.js"] = "gulpfile.js",
    ["gulpfile.mjs"] = "gulpfile.mjs",
    ["gulpfile.ts"] = "gulpfile.ts",
    ["gulpfile.cts"] = "gulpfile.cts",
    ["gulpfile.mts"] = "gulpfile.mts",
    ["gulpfile.babel.js"] = "gulpfile.babel.js",
    ["h"] = "h",
    [".hhconfig"] = ".hhconfig",
    ["haml"] = "haml",
    ["hbs"] = "hbs",
    ["mustache"] = "mustache",
    ["hardhat.config.js"] = "hardhat.config.js",
    ["hardhat.config.ts"] = "hardhat.config.ts",
    ["hs"] = "hs",
    ["hx"] = "hx",
    ["procfile"] = "procfile",
    ["procfile.windows"] = "procfile.windows",
    ["dat"] = "dat",
    ["bin"] = "bin",
    ["hex"] = "hex",
    ["hh"] = "hh",
    ["hpp"] = "hpp",
    ["hxx"] = "hxx",
    ["h++"] = "h++",
    ["hp"] = "hp",
    ["tcc"] = "tcc",
    ["inl"] = "inl",
    ["html"] = "html",
    ["htm"] = "htm",
    ["xhtml"] = "xhtml",
    ["html_vm"] = "html_vm",
    ["asp"] = "asp",
    ["http"] = "http",
    ["rest"] = "rest",
    ["huff"] = "huff",
    [".huskyrc"] = ".huskyrc",
    [".huskyrc.json"] = ".huskyrc.json",
    [".huskyrc.jsonc"] = ".huskyrc.jsonc",
    [".huskyrc.json5"] = ".huskyrc.json5",
    [".huskyrc.yaml"] = ".huskyrc.yaml",
    [".huskyrc.yml"] = ".huskyrc.yml",
    [".huskyrc.toml"] = ".huskyrc.toml",
    [".huskyrc.js"] = ".huskyrc.js",
    [".huskyrc.mjs"] = ".huskyrc.mjs",
    [".huskyrc.cjs"] = ".huskyrc.cjs",
    [".huskyrc.ts"] = ".huskyrc.ts",
    [".huskyrc.mts"] = ".huskyrc.mts",
    [".huskyrc.cts"] = ".huskyrc.cts",
    ["husky.config.json"] = "husky.config.json",
    ["husky.config.jsonc"] = "husky.config.jsonc",
    ["husky.config.json5"] = "husky.config.json5",
    ["husky.config.yaml"] = "husky.config.yaml",
    ["husky.config.yml"] = "husky.config.yml",
    ["husky.config.toml"] = "husky.config.toml",
    ["husky.config.js"] = "husky.config.js",
    ["husky.config.mjs"] = "husky.config.mjs",
    ["husky.config.cjs"] = "husky.config.cjs",
    ["husky.config.ts"] = "husky.config.ts",
    ["husky.config.mts"] = "husky.config.mts",
    ["husky.config.cts"] = "husky.config.cts",
    ["pot"] = "pot",
    ["po"] = "po",
    ["mo"] = "mo",
    ["lang"] = "lang",
    ["idr"] = "idr",
    ["ibc"] = "ibc",
    [".mincloudrc"] = ".mincloudrc",
    ["png"] = "png",
    ["jpeg"] = "jpeg",
    ["jpg"] = "jpg",
    ["gif"] = "gif",
    ["ico"] = "ico",
    ["tif"] = "tif",
    ["tiff"] = "tiff",
    ["psd"] = "psd",
    ["psb"] = "psb",
    ["ami"] = "ami",
    ["apx"] = "apx",
    ["avif"] = "avif",
    ["bmp"] = "bmp",
    ["bpg"] = "bpg",
    ["brk"] = "brk",
    ["cur"] = "cur",
    ["dds"] = "dds",
    ["dng"] = "dng",
    ["exr"] = "exr",
    ["fpx"] = "fpx",
    ["gbr"] = "gbr",
    ["img"] = "img",
    ["jbig2"] = "jbig2",
    ["jb2"] = "jb2",
    ["jng"] = "jng",
    ["jxr"] = "jxr",
    ["pgf"] = "pgf",
    ["pic"] = "pic",
    ["raw"] = "raw",
    ["webp"] = "webp",
    ["eps"] = "eps",
    ["afphoto"] = "afphoto",
    ["ase"] = "ase",
    ["aseprite"] = "aseprite",
    ["clip"] = "clip",
    ["cpt"] = "cpt",
    ["heif"] = "heif",
    ["heic"] = "heic",
    ["kra"] = "kra",
    ["mdp"] = "mdp",
    ["ora"] = "ora",
    ["pdn"] = "pdn",
    ["reb"] = "reb",
    ["sai"] = "sai",
    ["tga"] = "tga",
    ["xcf"] = "xcf",
    ["jfif"] = "jfif",
    ["ppm"] = "ppm",
    ["pbm"] = "pbm",
    ["pgm"] = "pgm",
    ["pnm"] = "pnm",
    ["icns"] = "icns",
    ["ionic.config.json"] = "ionic.config.json",
    [".io-config.json"] = ".io-config.json",
    [".nycrc"] = ".nycrc",
    [".nycrc.json"] = ".nycrc.json",
    [".nycrc.yaml"] = ".nycrc.yaml",
    [".nycrc.yml"] = ".nycrc.yml",
    ["nyc.config.js"] = "nyc.config.js",
    [".istanbul.yml"] = ".istanbul.yml",
    ["jar"] = "jar",
    ["java"] = "java",
    ["jsp"] = "jsp",
    ["class"] = "class",
    ["js.map"] = "js.map",
    ["mjs.map"] = "mjs.map",
    ["cjs.map"] = "cjs.map",
    ["jsconfig.json"] = "jsconfig.json",
    ["js"] = "js",
    ["esx"] = "esx",
    ["mjs"] = "mjs",
    ["jenkinsfile"] = "jenkinsfile",
    ["jenkins"] = "jenkins",
    ["jinja"] = "jinja",
    ["jinja2"] = "jinja2",
    ["j2"] = "j2",
    ["jinja-html"] = "jinja-html",
    ["json"] = "json",
    ["jsonc"] = "jsonc",
    ["tsbuildinfo"] = "tsbuildinfo",
    ["json5"] = "json5",
    ["jsonl"] = "jsonl",
    ["ndjson"] = "ndjson",
    [".jscsrc"] = ".jscsrc",
    [".jshintrc"] = ".jshintrc",
    ["composer.lock"] = "composer.lock",
    [".jsbeautifyrc"] = ".jsbeautifyrc",
    [".esformatter"] = ".esformatter",
    ["cdp.pid"] = "cdp.pid",
    [".lintstagedrc"] = ".lintstagedrc",
    [".whitesource"] = ".whitesource",
    ["jl"] = "jl",
    ["ipynb"] = "ipynb",
    ["karma.conf.js"] = "karma.conf.js",
    ["karma.conf.ts"] = "karma.conf.ts",
    ["karma.conf.coffee"] = "karma.conf.coffee",
    ["karma.config.js"] = "karma.config.js",
    ["karma.config.ts"] = "karma.config.ts",
    ["karma-main.js"] = "karma-main.js",
    ["karma-main.ts"] = "karma-main.ts",
    ["pub"] = "pub",
    ["key"] = "key",
    ["pem"] = "pem",
    ["asc"] = "asc",
    ["gpg"] = "gpg",
    ["passwd"] = "passwd",
    ["knip.json"] = "knip.json",
    ["knip.jsonc"] = "knip.jsonc",
    [".knip.json"] = ".knip.json",
    [".knip.jsonc"] = ".knip.jsonc",
    ["knip.ts"] = "knip.ts",
    ["knip.js"] = "knip.js",
    ["knip.config.ts"] = "knip.config.ts",
    ["knip.config.js"] = "knip.config.js",
    ["kt"] = "kt",
    ["kts"] = "kts",
    ["k8s.yml"] = "k8s.yml",
    ["k8s.yaml"] = "k8s.yaml",
    ["kubernetes.yml"] = "kubernetes.yml",
    ["kubernetes.yaml"] = "kubernetes.yaml",
    [".k8s.yml"] = ".k8s.yml",
    [".k8s.yaml"] = ".k8s.yaml",
    ["blade.php"] = "blade.php",
    ["inky.php"] = "inky.php",
    ["artisan"] = "artisan",
    ["less"] = "less",
    ["lib"] = "lib",
    ["bib"] = "bib",
    ["a"] = "a",
    [".lighthouserc.js"] = ".lighthouserc.js",
    ["lighthouserc.js"] = "lighthouserc.js",
    [".lighthouserc.cjs"] = ".lighthouserc.cjs",
    ["lighthouserc.cjs"] = "lighthouserc.cjs",
    [".lighthouserc.json"] = ".lighthouserc.json",
    ["lighthouserc.json"] = "lighthouserc.json",
    [".lighthouserc.yml"] = ".lighthouserc.yml",
    ["lighthouserc.yml"] = "lighthouserc.yml",
    [".lighthouserc.yaml"] = ".lighthouserc.yaml",
    ["lighthouserc.yaml"] = "lighthouserc.yaml",
    ["ly"] = "ly",
    ["liquid"] = "liquid",
    ["lisp"] = "lisp",
    ["lsp"] = "lsp",
    ["cl"] = "cl",
    ["fast"] = "fast",
    ["ls"] = "ls",
    ["lock"] = "lock",
    ["security.md"] = "security.md",
    ["security.txt"] = "security.txt",
    ["security"] = "security",
    ["log"] = "log",
    ["lol"] = "lol",
    ["lua"] = "lua",
    [".luacheckrc"] = ".luacheckrc",
    ["makefile"] = "makefile",
    ["gnumakefile"] = "gnumakefile",
    ["kbuild"] = "kbuild",
    ["md"] = "md",
    ["markdown"] = "markdown",
    ["rst"] = "rst",
    ["maven.config"] = "maven.config",
    ["jvm.config"] = "jvm.config",
    ["pom.xml"] = "pom.xml",
    ["svx"] = "svx",
    ["mdx"] = "mdx",
    ["merlin"] = "merlin",
    ["mcfunction"] = "mcfunction",
    ["mcmeta"] = "mcmeta",
    ["mcr"] = "mcr",
    ["mca"] = "mca",
    ["mcgame"] = "mcgame",
    ["mclevel"] = "mclevel",
    ["mcworld"] = "mcworld",
    ["mine"] = "mine",
    ["mus"] = "mus",
    ["mcstructure"] = "mcstructure",
    ["mcpack"] = "mcpack",
    ["mcaddon"] = "mcaddon",
    ["mctemplate"] = "mctemplate",
    ["mcproject"] = "mcproject",
    [".mcattributes"] = ".mcattributes",
    [".mcdefinitions"] = ".mcdefinitions",
    [".mcignore"] = ".mcignore",
    ["mint"] = "mint",
    ["mocha.opts"] = "mocha.opts",
    [".mocharc.yml"] = ".mocharc.yml",
    [".mocharc.yaml"] = ".mocharc.yaml",
    [".mocharc.js"] = ".mocharc.js",
    [".mocharc.json"] = ".mocharc.json",
    [".mocharc.jsonc"] = ".mocharc.jsonc",
    [".modernizrrc"] = ".modernizrrc",
    [".modernizrrc.js"] = ".modernizrrc.js",
    [".modernizrrc.json"] = ".modernizrrc.json",
    ["mojo"] = "mojo",
    ["moon.yml"] = "moon.yml",
    ["moon"] = "moon",
    ["mxml"] = "mxml",
    ["nginx"] = "nginx",
    ["nginxconf"] = "nginxconf",
    ["nginxconfig"] = "nginxconfig",
    ["nginx.conf"] = "nginx.conf",
    ["nim"] = "nim",
    ["nimble"] = "nimble",
    ["nix"] = "nix",
    ["package.json"] = "package.json",
    [".nvmrc"] = ".nvmrc",
    [".esmrc"] = ".esmrc",
    [".node-version"] = ".node-version",
    ["package-lock.json"] = "package-lock.json",
    [".npmignore"] = ".npmignore",
    [".npmrc"] = ".npmrc",
    ["njk"] = "njk",
    ["nunjucks"] = "nunjucks",
    ["nuxt.config.js"] = "nuxt.config.js",
    ["nuxt.config.ts"] = "nuxt.config.ts",
    [".nuxtignore"] = ".nuxtignore",
    ["ml"] = "ml",
    ["mli"] = "mli",
    ["cmx"] = "cmx",
    ["opam"] = "opam",
    ["panda.config.ts"] = "panda.config.ts",
    ["panda.config.js"] = "panda.config.js",
    ["panda.config.mjs"] = "panda.config.mjs",
    ["panda.config.mts"] = "panda.config.mts",
    ["panda.config.cjs"] = "panda.config.cjs",
    [".parcelrc"] = ".parcelrc",
    ["pas"] = "pas",
    ["pwn"] = "pwn",
    ["amx"] = "amx",
    ["pdf"] = "pdf",
    ["pm"] = "pm",
    ["raku"] = "raku",
    [".php_cs"] = ".php_cs",
    [".php_cs.dist"] = ".php_cs.dist",
    [".php_cs.php"] = ".php_cs.php",
    [".php_cs.dist.php"] = ".php_cs.dist.php",
    [".php-cs-fixer.php"] = ".php-cs-fixer.php",
    [".php-cs-fixer.dist.php"] = ".php-cs-fixer.dist.php",
    ["php"] = "php",
    ["pine"] = "pine",
    ["pipeline"] = "pipeline",
    ["pkl"] = "pkl",
    ["PklProject"] = "PklProject",
    ["PklProject.deps.json"] = "PklProject.deps.json",
    ["playwright.config.js"] = "playwright.config.js",
    ["playwright.config.mjs"] = "playwright.config.mjs",
    ["playwright.config.ts"] = "playwright.config.ts",
    ["playwright.config.base.js"] = "playwright.config.base.js",
    ["playwright.config.base.mjs"] = "playwright.config.base.mjs",
    ["playwright.config.base.ts"] = "playwright.config.base.ts",
    ["playwright-ct.config.js"] = "playwright-ct.config.js",
    ["playwright-ct.config.mjs"] = "playwright-ct.config.mjs",
    ["playwright-ct.config.ts"] = "playwright-ct.config.ts",
    ["plopfile.js"] = "plopfile.js",
    ["plopfile.cjs"] = "plopfile.cjs",
    ["plopfile.mjs"] = "plopfile.mjs",
    ["plopfile.ts"] = "plopfile.ts",
    ["pptx"] = "pptx",
    ["ppt"] = "ppt",
    ["pptm"] = "pptm",
    ["potx"] = "potx",
    ["potm"] = "potm",
    ["ppsx"] = "ppsx",
    ["ppsm"] = "ppsm",
    ["pps"] = "pps",
    ["ppam"] = "ppam",
    ["ppa"] = "ppa",
    ["odp"] = "odp",
    ["ps1"] = "ps1",
    ["psm1"] = "psm1",
    ["psd1"] = "psd1",
    ["ps1xml"] = "ps1xml",
    ["psc1"] = "psc1",
    ["pssc"] = "pssc",
    [".prettierrc"] = ".prettierrc",
    [".prettierrc.json"] = ".prettierrc.json",
    [".prettierrc.jsonc"] = ".prettierrc.jsonc",
    [".prettierrc.json5"] = ".prettierrc.json5",
    [".prettierrc.yaml"] = ".prettierrc.yaml",
    [".prettierrc.yml"] = ".prettierrc.yml",
    [".prettierrc.toml"] = ".prettierrc.toml",
    [".prettierrc.js"] = ".prettierrc.js",
    [".prettierrc.mjs"] = ".prettierrc.mjs",
    [".prettierrc.cjs"] = ".prettierrc.cjs",
    [".prettierrc.ts"] = ".prettierrc.ts",
    [".prettierrc.mts"] = ".prettierrc.mts",
    [".prettierrc.cts"] = ".prettierrc.cts",
    ["prettier.config.json"] = "prettier.config.json",
    ["prettier.config.jsonc"] = "prettier.config.jsonc",
    ["prettier.config.json5"] = "prettier.config.json5",
    ["prettier.config.yaml"] = "prettier.config.yaml",
    ["prettier.config.yml"] = "prettier.config.yml",
    ["prettier.config.toml"] = "prettier.config.toml",
    ["prettier.config.js"] = "prettier.config.js",
    ["prettier.config.mjs"] = "prettier.config.mjs",
    ["prettier.config.cjs"] = "prettier.config.cjs",
    ["prettier.config.ts"] = "prettier.config.ts",
    ["prettier.config.mts"] = "prettier.config.mts",
    ["prettier.config.cts"] = "prettier.config.cts",
    [".prettierignore"] = ".prettierignore",
    ["prisma"] = "prisma",
    ["prisma.yml"] = "prisma.yml",
    ["p"] = "p",
    ["pro"] = "pro",
    ["pl"] = "pl",
    ["jade"] = "jade",
    ["pug"] = "pug",
    [".pug-lintrc"] = ".pug-lintrc",
    [".pug-lintrc.js"] = ".pug-lintrc.js",
    [".pug-lintrc.json"] = ".pug-lintrc.json",
    ["puppet"] = "puppet",
    ["pure"] = "pure",
    ["purs"] = "purs",
    ["py"] = "py",
    ["qml"] = "qml",
    ["r"] = "r",
    ["rmd"] = "rmd",
    [".Rhistory"] = ".Rhistory",
    ["raml"] = "raml",
    ["cshtml"] = "cshtml",
    ["vbhtml"] = "vbhtml",
    ["tsx"] = "tsx",
    ["jsx"] = "jsx",
    ["readme.md"] = "readme.md",
    ["readme.rst"] = "readme.rst",
    ["readme.txt"] = "readme.txt",
    ["readme"] = "readme",
    ["reason"] = "reason",
    ["reason_lisp"] = "reason_lisp",
    [".renovaterc"] = ".renovaterc",
    [".renovaterc.json"] = ".renovaterc.json",
    ["renovate-config.json"] = "renovate-config.json",
    ["renovate.json"] = "renovate.json",
    ["renovate.json5"] = "renovate.json5",
    ["resi"] = "resi",
    ["res"] = "res",
    ["roadmap.md"] = "roadmap.md",
    ["roadmap.txt"] = "roadmap.txt",
    ["timeline.md"] = "timeline.md",
    ["timeline.txt"] = "timeline.txt",
    ["milestones.md"] = "milestones.md",
    ["milestones.txt"] = "milestones.txt",
    ["robot"] = "robot",
    ["robots.txt"] = "robots.txt",
    ["rollup.config.js"] = "rollup.config.js",
    ["rollup.config.mjs"] = "rollup.config.mjs",
    ["rollup.config.ts"] = "rollup.config.ts",
    ["rollup-config.js"] = "rollup-config.js",
    ["rollup-config.mjs"] = "rollup-config.mjs",
    ["rollup-config.ts"] = "rollup-config.ts",
    ["rollup.config.common.js"] = "rollup.config.common.js",
    ["rollup.config.common.mjs"] = "rollup.config.common.mjs",
    ["rollup.config.common.ts"] = "rollup.config.common.ts",
    ["rollup.config.base.js"] = "rollup.config.base.js",
    ["rollup.config.base.mjs"] = "rollup.config.base.mjs",
    ["rollup.config.base.ts"] = "rollup.config.base.ts",
    ["rollup.config.prod.js"] = "rollup.config.prod.js",
    ["rollup.config.prod.mjs"] = "rollup.config.prod.mjs",
    ["rollup.config.prod.ts"] = "rollup.config.prod.ts",
    ["rollup.config.dev.js"] = "rollup.config.dev.js",
    ["rollup.config.dev.mjs"] = "rollup.config.dev.mjs",
    ["rollup.config.dev.ts"] = "rollup.config.dev.ts",
    ["rollup.config.prod.vendor.js"] = "rollup.config.prod.vendor.js",
    ["rollup.config.prod.vendor.mjs"] = "rollup.config.prod.vendor.mjs",
    ["rollup.config.prod.vendor.ts"] = "rollup.config.prod.vendor.ts",
    ["routing.ts"] = "routing.ts",
    ["routing.tsx"] = "routing.tsx",
    ["routing.js"] = "routing.js",
    ["routing.jsx"] = "routing.jsx",
    ["routes.ts"] = "routes.ts",
    ["routes.tsx"] = "routes.tsx",
    ["routes.js"] = "routes.js",
    ["routes.jsx"] = "routes.jsx",
    ["rb"] = "rb",
    ["erb"] = "erb",
    ["rbs"] = "rbs",
    ["rs"] = "rs",
    ["ron"] = "ron",
    ["scss"] = "scss",
    ["sass"] = "sass",
    ["sbt"] = "sbt",
    ["scala"] = "scala",
    ["sc"] = "sc",
    ["ss"] = "ss",
    ["scm"] = "scm",
    ["code-search"] = "code-search",
    [".jshintignore"] = ".jshintignore",
    [".buildignore"] = ".buildignore",
    [".mrconfig"] = ".mrconfig",
    [".yardopts"] = ".yardopts",
    ["manifest.mf"] = "manifest.mf",
    [".clang-format"] = ".clang-format",
    [".clang-tidy"] = ".clang-tidy",
    ["ini"] = "ini",
    ["dlc"] = "dlc",
    ["config"] = "config",
    ["conf"] = "conf",
    ["properties"] = "properties",
    ["prop"] = "prop",
    ["settings"] = "settings",
    ["option"] = "option",
    ["props"] = "props",
    ["toml"] = "toml",
    ["prefs"] = "prefs",
    ["sln.dotsettings"] = "sln.dotsettings",
    ["sln.dotsettings.user"] = "sln.dotsettings.user",
    ["cfg"] = "cfg",
    ["unity"] = "unity",
    ["sketch"] = "sketch",
    ["slim"] = "slim",
    [".slugignore"] = ".slugignore",
    ["tpl"] = "tpl",
    ["sol"] = "sol",
    ["stryker.conf.json"] = "stryker.conf.json",
    ["stryker.conf.js"] = "stryker.conf.js",
    ["stryker.conf.cjs"] = "stryker.conf.cjs",
    ["stryker.conf.mjs"] = "stryker.conf.mjs",
    [".stryker.conf.json"] = ".stryker.conf.json",
    [".stryker.conf.js"] = ".stryker.conf.js",
    [".stryker.conf.cjs"] = ".stryker.conf.cjs",
    [".stryker.conf.mjs"] = ".stryker.conf.mjs",
    [".stylelintrc"] = ".stylelintrc",
    [".stylelintrc.json"] = ".stylelintrc.json",
    [".stylelintrc.jsonc"] = ".stylelintrc.jsonc",
    [".stylelintrc.json5"] = ".stylelintrc.json5",
    [".stylelintrc.yaml"] = ".stylelintrc.yaml",
    [".stylelintrc.yml"] = ".stylelintrc.yml",
    [".stylelintrc.toml"] = ".stylelintrc.toml",
    [".stylelintrc.js"] = ".stylelintrc.js",
    [".stylelintrc.mjs"] = ".stylelintrc.mjs",
    [".stylelintrc.cjs"] = ".stylelintrc.cjs",
    [".stylelintrc.ts"] = ".stylelintrc.ts",
    [".stylelintrc.mts"] = ".stylelintrc.mts",
    [".stylelintrc.cts"] = ".stylelintrc.cts",
    ["stylelint.config.json"] = "stylelint.config.json",
    ["stylelint.config.jsonc"] = "stylelint.config.jsonc",
    ["stylelint.config.json5"] = "stylelint.config.json5",
    ["stylelint.config.yaml"] = "stylelint.config.yaml",
    ["stylelint.config.yml"] = "stylelint.config.yml",
    ["stylelint.config.toml"] = "stylelint.config.toml",
    ["stylelint.config.js"] = "stylelint.config.js",
    ["stylelint.config.mjs"] = "stylelint.config.mjs",
    ["stylelint.config.cjs"] = "stylelint.config.cjs",
    ["stylelint.config.ts"] = "stylelint.config.ts",
    ["stylelint.config.mts"] = "stylelint.config.mts",
    ["stylelint.config.cts"] = "stylelint.config.cts",
    [".stylelintignore"] = ".stylelintignore",
    [".stylelintcache"] = ".stylelintcache",
    ["styl"] = "styl",
    ["sublime-project"] = "sublime-project",
    ["sublime-workspace"] = "sublime-workspace",
    ["svelte"] = "svelte",
    ["svelte.config.js"] = "svelte.config.js",
    ["svelte.config.cjs"] = "svelte.config.cjs",
    ["svg"] = "svg",
    [".svgrrc"] = ".svgrrc",
    [".svgrrc.json"] = ".svgrrc.json",
    [".svgrrc.jsonc"] = ".svgrrc.jsonc",
    [".svgrrc.json5"] = ".svgrrc.json5",
    [".svgrrc.yaml"] = ".svgrrc.yaml",
    [".svgrrc.yml"] = ".svgrrc.yml",
    [".svgrrc.toml"] = ".svgrrc.toml",
    [".svgrrc.js"] = ".svgrrc.js",
    [".svgrrc.mjs"] = ".svgrrc.mjs",
    [".svgrrc.cjs"] = ".svgrrc.cjs",
    [".svgrrc.ts"] = ".svgrrc.ts",
    [".svgrrc.mts"] = ".svgrrc.mts",
    [".svgrrc.cts"] = ".svgrrc.cts",
    ["svgr.config.json"] = "svgr.config.json",
    ["svgr.config.jsonc"] = "svgr.config.jsonc",
    ["svgr.config.json5"] = "svgr.config.json5",
    ["svgr.config.yaml"] = "svgr.config.yaml",
    ["svgr.config.yml"] = "svgr.config.yml",
    ["svgr.config.toml"] = "svgr.config.toml",
    ["svgr.config.js"] = "svgr.config.js",
    ["svgr.config.mjs"] = "svgr.config.mjs",
    ["svgr.config.cjs"] = "svgr.config.cjs",
    ["svgr.config.ts"] = "svgr.config.ts",
    ["svgr.config.mts"] = "svgr.config.mts",
    ["svgr.config.cts"] = "svgr.config.cts",
    ["swagger.json"] = "swagger.json",
    ["swagger.yml"] = "swagger.yml",
    ["swagger.yaml"] = "swagger.yaml",
    ["swift"] = "swift",
    [".syncpackrc"] = ".syncpackrc",
    [".syncpackrc.json"] = ".syncpackrc.json",
    [".syncpackrc.jsonc"] = ".syncpackrc.jsonc",
    [".syncpackrc.json5"] = ".syncpackrc.json5",
    [".syncpackrc.yaml"] = ".syncpackrc.yaml",
    [".syncpackrc.yml"] = ".syncpackrc.yml",
    [".syncpackrc.toml"] = ".syncpackrc.toml",
    [".syncpackrc.js"] = ".syncpackrc.js",
    [".syncpackrc.mjs"] = ".syncpackrc.mjs",
    [".syncpackrc.cjs"] = ".syncpackrc.cjs",
    [".syncpackrc.ts"] = ".syncpackrc.ts",
    [".syncpackrc.mts"] = ".syncpackrc.mts",
    [".syncpackrc.cts"] = ".syncpackrc.cts",
    ["syncpack.config.json"] = "syncpack.config.json",
    ["syncpack.config.jsonc"] = "syncpack.config.jsonc",
    ["syncpack.config.json5"] = "syncpack.config.json5",
    ["syncpack.config.yaml"] = "syncpack.config.yaml",
    ["syncpack.config.yml"] = "syncpack.config.yml",
    ["syncpack.config.toml"] = "syncpack.config.toml",
    ["syncpack.config.js"] = "syncpack.config.js",
    ["syncpack.config.mjs"] = "syncpack.config.mjs",
    ["syncpack.config.cjs"] = "syncpack.config.cjs",
    ["syncpack.config.ts"] = "syncpack.config.ts",
    ["syncpack.config.mts"] = "syncpack.config.mts",
    ["syncpack.config.cts"] = "syncpack.config.cts",
    ["xlsx"] = "xlsx",
    ["xlsm"] = "xlsm",
    ["xls"] = "xls",
    ["csv"] = "csv",
    ["tsv"] = "tsv",
    ["psv"] = "psv",
    ["ods"] = "ods",
    ["tailwind.js"] = "tailwind.js",
    ["tailwind.ts"] = "tailwind.ts",
    ["tailwind.config.js"] = "tailwind.config.js",
    ["tailwind.config.cjs"] = "tailwind.config.cjs",
    ["tailwind.config.mjs"] = "tailwind.config.mjs",
    ["tailwind.config.ts"] = "tailwind.config.ts",
    ["tailwind.config.cts"] = "tailwind.config.cts",
    ["tailwind.config.mts"] = "tailwind.config.mts",
    ["taskfile.yml"] = "taskfile.yml",
    ["taskfile.yaml"] = "taskfile.yaml",
    ["taskfile.dist.yml"] = "taskfile.dist.yml",
    ["taskfile.dist.yaml"] = "taskfile.dist.yaml",
    ["tcl"] = "tcl",
    ["templ"] = "templ",
    ["template"] = "template",
    ["tf"] = "tf",
    ["tf.json"] = "tf.json",
    ["tfvars"] = "tfvars",
    ["tfstate"] = "tfstate",
    ["tfbackend"] = "tfbackend",
    ["spec.js"] = "spec.js",
    ["spec.cjs"] = "spec.cjs",
    ["spec.mjs"] = "spec.mjs",
    ["e2e-spec.js"] = "e2e-spec.js",
    ["e2e-spec.cjs"] = "e2e-spec.cjs",
    ["e2e-spec.mjs"] = "e2e-spec.mjs",
    ["test.js"] = "test.js",
    ["test.cjs"] = "test.cjs",
    ["test.mjs"] = "test.mjs",
    ["js.snap"] = "js.snap",
    ["cy.js"] = "cy.js",
    ["spec.jsx"] = "spec.jsx",
    ["test.jsx"] = "test.jsx",
    ["jsx.snap"] = "jsx.snap",
    ["cy.jsx"] = "cy.jsx",
    ["spec.tsx"] = "spec.tsx",
    ["test.tsx"] = "test.tsx",
    ["tsx.snap"] = "tsx.snap",
    ["cy.tsx"] = "cy.tsx",
    ["spec-d.tsx"] = "spec-d.tsx",
    ["test-d.tsx"] = "test-d.tsx",
    ["tex"] = "tex",
    ["sty"] = "sty",
    ["dtx"] = "dtx",
    ["ltx"] = "ltx",
    ["todo"] = "todo",
    ["todo.md"] = "todo.md",
    ["todos.md"] = "todos.md",
    [".travis.yml"] = ".travis.yml",
    ["tree"] = "tree",
    ["tsconfig.json"] = "tsconfig.json",
    ["tsconfig.app.json"] = "tsconfig.app.json",
    ["tsconfig.editor.json"] = "tsconfig.editor.json",
    ["tsconfig.spec.json"] = "tsconfig.spec.json",
    ["tsconfig.base.json"] = "tsconfig.base.json",
    ["tsconfig.build.json"] = "tsconfig.build.json",
    ["tsconfig.eslint.json"] = "tsconfig.eslint.json",
    ["tsconfig.lib.json"] = "tsconfig.lib.json",
    ["tsconfig.lib.prod.json"] = "tsconfig.lib.prod.json",
    ["tsconfig.node.json"] = "tsconfig.node.json",
    ["tsconfig.test.json"] = "tsconfig.test.json",
    ["tsconfig.e2e.json"] = "tsconfig.e2e.json",
    ["tsconfig.web.json"] = "tsconfig.web.json",
    ["tsconfig.webworker.json"] = "tsconfig.webworker.json",
    ["tsconfig.worker.json"] = "tsconfig.worker.json",
    ["tsconfig.config.json"] = "tsconfig.config.json",
    ["tsconfig.vitest.json"] = "tsconfig.vitest.json",
    ["tsconfig.cjs.json"] = "tsconfig.cjs.json",
    ["tsconfig.esm.json"] = "tsconfig.esm.json",
    ["tsconfig.mjs.json"] = "tsconfig.mjs.json",
    ["tsconfig.doc.json"] = "tsconfig.doc.json",
    ["tsconfig.paths.json"] = "tsconfig.paths.json",
    ["tsconfig.main.json"] = "tsconfig.main.json",
    ["tsconfig.renderer.json"] = "tsconfig.renderer.json",
    ["tsconfig.server.json"] = "tsconfig.server.json",
    ["d.ts"] = "d.ts",
    ["d.cts"] = "d.cts",
    ["d.mts"] = "d.mts",
    [".env"] = ".env",
    [".env.defaults"] = ".env.defaults",
    [".env.example"] = ".env.example",
    [".env.sample"] = ".env.sample",
    [".env.template"] = ".env.template",
    [".env.schema"] = ".env.schema",
    [".env.local"] = ".env.local",
    [".env.dev"] = ".env.dev",
    [".env.development"] = ".env.development",
    [".env.alpha"] = ".env.alpha",
    [".env.e2e"] = ".env.e2e",
    [".env.qa"] = ".env.qa",
    [".env.dist"] = ".env.dist",
    [".env.prod"] = ".env.prod",
    [".env.production"] = ".env.production",
    [".env.stage"] = ".env.stage",
    [".env.staging"] = ".env.staging",
    [".env.preview"] = ".env.preview",
    [".env.test"] = ".env.test",
    [".env.testing"] = ".env.testing",
    [".env.development.local"] = ".env.development.local",
    [".env.qa.local"] = ".env.qa.local",
    [".env.production.local"] = ".env.production.local",
    [".env.staging.local"] = ".env.staging.local",
    [".env.test.local"] = ".env.test.local",
    [".env.uat"] = ".env.uat",
    ["twig"] = "twig",
    ["ts"] = "ts",
    ["uproject"] = "uproject",
    ["url"] = "url",
    ["vercel.json"] = "vercel.json",
    [".vercelignore"] = ".vercelignore",
    ["now.json"] = "now.json",
    [".nowignore"] = ".nowignore",
    ["vhd"] = "vhd",
    ["sv"] = "sv",
    ["svh"] = "svh",
    ["webm"] = "webm",
    ["mkv"] = "mkv",
    ["flv"] = "flv",
    ["vob"] = "vob",
    ["ogv"] = "ogv",
    ["ogg"] = "ogg",
    ["gifv"] = "gifv",
    ["avi"] = "avi",
    ["mov"] = "mov",
    ["qt"] = "qt",
    ["wmv"] = "wmv",
    ["yuv"] = "yuv",
    ["rm"] = "rm",
    ["rmvb"] = "rmvb",
    ["mp4"] = "mp4",
    ["m4v"] = "m4v",
    ["mpg"] = "mpg",
    ["mp2"] = "mp2",
    ["mpeg"] = "mpeg",
    ["mpe"] = "mpe",
    ["mpv"] = "mpv",
    ["m2v"] = "m2v",
    ["vimrc"] = "vimrc",
    ["gvimrc"] = "gvimrc",
    ["exrc"] = "exrc",
    ["vim"] = "vim",
    ["viminfo"] = "viminfo",
    ["vdi"] = "vdi",
    ["vbox"] = "vbox",
    ["vbox-prev"] = "vbox-prev",
    ["csproj"] = "csproj",
    ["ruleset"] = "ruleset",
    ["sln"] = "sln",
    ["slnx"] = "slnx",
    ["suo"] = "suo",
    ["vb"] = "vb",
    ["vbs"] = "vbs",
    ["vcxitems"] = "vcxitems",
    ["vcxitems.filters"] = "vcxitems.filters",
    ["vcxproj"] = "vcxproj",
    ["vcxproj.filters"] = "vcxproj.filters",
    ["vite.config.js"] = "vite.config.js",
    ["vite.config.mjs"] = "vite.config.mjs",
    ["vite.config.cjs"] = "vite.config.cjs",
    ["vite.config.ts"] = "vite.config.ts",
    ["vite.config.cts"] = "vite.config.cts",
    ["vite.config.mts"] = "vite.config.mts",
    ["v"] = "v",
    ["vpkg.json"] = "vpkg.json",
    ["v.mod"] = "v.mod",
    ["vscodeignore"] = "vscodeignore",
    ["vsixmanifest"] = "vsixmanifest",
    ["vsix"] = "vsix",
    ["code-workplace"] = "code-workplace",
    ["code-workspace"] = "code-workspace",
    ["code-profile"] = "code-profile",
    ["code-snippets"] = "code-snippets",
    ["vue.config.js"] = "vue.config.js",
    ["vue.config.ts"] = "vue.config.ts",
    ["vetur.config.js"] = "vetur.config.js",
    ["vetur.config.ts"] = "vetur.config.ts",
    ["volar.config.js"] = "volar.config.js",
    ["vue"] = "vue",
    ["wat"] = "wat",
    ["wasm"] = "wasm",
    ["webpack.base.js"] = "webpack.base.js",
    ["webpack.base.mjs"] = "webpack.base.mjs",
    ["webpack.base.cjs"] = "webpack.base.cjs",
    ["webpack.base.ts"] = "webpack.base.ts",
    ["webpack.base.mts"] = "webpack.base.mts",
    ["webpack.base.cts"] = "webpack.base.cts",
    ["webpack.client.js"] = "webpack.client.js",
    ["webpack.client.mjs"] = "webpack.client.mjs",
    ["webpack.client.cjs"] = "webpack.client.cjs",
    ["webpack.client.ts"] = "webpack.client.ts",
    ["webpack.client.mts"] = "webpack.client.mts",
    ["webpack.client.cts"] = "webpack.client.cts",
    ["webpack.common.js"] = "webpack.common.js",
    ["webpack.common.mjs"] = "webpack.common.mjs",
    ["webpack.common.cjs"] = "webpack.common.cjs",
    ["webpack.common.ts"] = "webpack.common.ts",
    ["webpack.common.mts"] = "webpack.common.mts",
    ["webpack.common.cts"] = "webpack.common.cts",
    ["webpack.config.babel.js"] = "webpack.config.babel.js",
    ["webpack.config.babel.mjs"] = "webpack.config.babel.mjs",
    ["webpack.config.babel.cjs"] = "webpack.config.babel.cjs",
    ["webpack.config.babel.ts"] = "webpack.config.babel.ts",
    ["webpack.config.babel.mts"] = "webpack.config.babel.mts",
    ["webpack.config.babel.cts"] = "webpack.config.babel.cts",
    ["webpack.config.base.babel.js"] = "webpack.config.base.babel.js",
    ["webpack.config.base.babel.mjs"] = "webpack.config.base.babel.mjs",
    ["webpack.config.base.babel.cjs"] = "webpack.config.base.babel.cjs",
    ["webpack.config.base.babel.ts"] = "webpack.config.base.babel.ts",
    ["webpack.config.base.babel.mts"] = "webpack.config.base.babel.mts",
    ["webpack.config.base.babel.cts"] = "webpack.config.base.babel.cts",
    ["webpack.config.base.js"] = "webpack.config.base.js",
    ["webpack.config.base.mjs"] = "webpack.config.base.mjs",
    ["webpack.config.base.cjs"] = "webpack.config.base.cjs",
    ["webpack.config.base.ts"] = "webpack.config.base.ts",
    ["webpack.config.base.mts"] = "webpack.config.base.mts",
    ["webpack.config.base.cts"] = "webpack.config.base.cts",
    ["webpack.config.client.js"] = "webpack.config.client.js",
    ["webpack.config.client.mjs"] = "webpack.config.client.mjs",
    ["webpack.config.client.cjs"] = "webpack.config.client.cjs",
    ["webpack.config.client.ts"] = "webpack.config.client.ts",
    ["webpack.config.client.mts"] = "webpack.config.client.mts",
    ["webpack.config.client.cts"] = "webpack.config.client.cts",
    ["webpack.config.common.babel.js"] = "webpack.config.common.babel.js",
    ["webpack.config.common.babel.mjs"] = "webpack.config.common.babel.mjs",
    ["webpack.config.common.babel.cjs"] = "webpack.config.common.babel.cjs",
    ["webpack.config.common.babel.ts"] = "webpack.config.common.babel.ts",
    ["webpack.config.common.babel.mts"] = "webpack.config.common.babel.mts",
    ["webpack.config.common.babel.cts"] = "webpack.config.common.babel.cts",
    ["webpack.config.common.js"] = "webpack.config.common.js",
    ["webpack.config.common.mjs"] = "webpack.config.common.mjs",
    ["webpack.config.common.cjs"] = "webpack.config.common.cjs",
    ["webpack.config.common.ts"] = "webpack.config.common.ts",
    ["webpack.config.common.mts"] = "webpack.config.common.mts",
    ["webpack.config.common.cts"] = "webpack.config.common.cts",
    ["webpack.config.dev.babel.js"] = "webpack.config.dev.babel.js",
    ["webpack.config.dev.babel.mjs"] = "webpack.config.dev.babel.mjs",
    ["webpack.config.dev.babel.cjs"] = "webpack.config.dev.babel.cjs",
    ["webpack.config.dev.babel.ts"] = "webpack.config.dev.babel.ts",
    ["webpack.config.dev.babel.mts"] = "webpack.config.dev.babel.mts",
    ["webpack.config.dev.babel.cts"] = "webpack.config.dev.babel.cts",
    ["webpack.config.dev.js"] = "webpack.config.dev.js",
    ["webpack.config.dev.mjs"] = "webpack.config.dev.mjs",
    ["webpack.config.dev.cjs"] = "webpack.config.dev.cjs",
    ["webpack.config.dev.ts"] = "webpack.config.dev.ts",
    ["webpack.config.dev.mts"] = "webpack.config.dev.mts",
    ["webpack.config.dev.cts"] = "webpack.config.dev.cts",
    ["webpack.config.main.js"] = "webpack.config.main.js",
    ["webpack.config.main.mjs"] = "webpack.config.main.mjs",
    ["webpack.config.main.cjs"] = "webpack.config.main.cjs",
    ["webpack.config.main.ts"] = "webpack.config.main.ts",
    ["webpack.config.main.mts"] = "webpack.config.main.mts",
    ["webpack.config.main.cts"] = "webpack.config.main.cts",
    ["webpack.config.prod.babel.js"] = "webpack.config.prod.babel.js",
    ["webpack.config.prod.babel.mjs"] = "webpack.config.prod.babel.mjs",
    ["webpack.config.prod.babel.cjs"] = "webpack.config.prod.babel.cjs",
    ["webpack.config.prod.babel.ts"] = "webpack.config.prod.babel.ts",
    ["webpack.config.prod.babel.mts"] = "webpack.config.prod.babel.mts",
    ["webpack.config.prod.babel.cts"] = "webpack.config.prod.babel.cts",
    ["webpack.config.prod.js"] = "webpack.config.prod.js",
    ["webpack.config.prod.mjs"] = "webpack.config.prod.mjs",
    ["webpack.config.prod.cjs"] = "webpack.config.prod.cjs",
    ["webpack.config.prod.ts"] = "webpack.config.prod.ts",
    ["webpack.config.prod.mts"] = "webpack.config.prod.mts",
    ["webpack.config.prod.cts"] = "webpack.config.prod.cts",
    ["webpack.config.production.babel.js"] = "webpack.config.production.babel.js",
    ["webpack.config.production.babel.mjs"] = "webpack.config.production.babel.mjs",
    ["webpack.config.production.babel.cjs"] = "webpack.config.production.babel.cjs",
    ["webpack.config.production.babel.ts"] = "webpack.config.production.babel.ts",
    ["webpack.config.production.babel.mts"] = "webpack.config.production.babel.mts",
    ["webpack.config.production.babel.cts"] = "webpack.config.production.babel.cts",
    ["webpack.config.production.js"] = "webpack.config.production.js",
    ["webpack.config.production.mjs"] = "webpack.config.production.mjs",
    ["webpack.config.production.cjs"] = "webpack.config.production.cjs",
    ["webpack.config.production.ts"] = "webpack.config.production.ts",
    ["webpack.config.production.mts"] = "webpack.config.production.mts",
    ["webpack.config.production.cts"] = "webpack.config.production.cts",
    ["webpack.config.renderer.js"] = "webpack.config.renderer.js",
    ["webpack.config.renderer.mjs"] = "webpack.config.renderer.mjs",
    ["webpack.config.renderer.cjs"] = "webpack.config.renderer.cjs",
    ["webpack.config.renderer.ts"] = "webpack.config.renderer.ts",
    ["webpack.config.renderer.mts"] = "webpack.config.renderer.mts",
    ["webpack.config.renderer.cts"] = "webpack.config.renderer.cts",
    ["webpack.config.server.js"] = "webpack.config.server.js",
    ["webpack.config.server.mjs"] = "webpack.config.server.mjs",
    ["webpack.config.server.cjs"] = "webpack.config.server.cjs",
    ["webpack.config.server.ts"] = "webpack.config.server.ts",
    ["webpack.config.server.mts"] = "webpack.config.server.mts",
    ["webpack.config.server.cts"] = "webpack.config.server.cts",
    ["webpack.config.staging.babel.js"] = "webpack.config.staging.babel.js",
    ["webpack.config.staging.babel.mjs"] = "webpack.config.staging.babel.mjs",
    ["webpack.config.staging.babel.cjs"] = "webpack.config.staging.babel.cjs",
    ["webpack.config.staging.babel.ts"] = "webpack.config.staging.babel.ts",
    ["webpack.config.staging.babel.mts"] = "webpack.config.staging.babel.mts",
    ["webpack.config.staging.babel.cts"] = "webpack.config.staging.babel.cts",
    ["webpack.config.staging.js"] = "webpack.config.staging.js",
    ["webpack.config.staging.mjs"] = "webpack.config.staging.mjs",
    ["webpack.config.staging.cjs"] = "webpack.config.staging.cjs",
    ["webpack.config.staging.ts"] = "webpack.config.staging.ts",
    ["webpack.config.staging.mts"] = "webpack.config.staging.mts",
    ["webpack.config.staging.cts"] = "webpack.config.staging.cts",
    ["webpack.config.test.js"] = "webpack.config.test.js",
    ["webpack.config.test.mjs"] = "webpack.config.test.mjs",
    ["webpack.config.test.cjs"] = "webpack.config.test.cjs",
    ["webpack.config.test.ts"] = "webpack.config.test.ts",
    ["webpack.config.test.mts"] = "webpack.config.test.mts",
    ["webpack.config.test.cts"] = "webpack.config.test.cts",
    ["webpack.config.vendor.production.js"] = "webpack.config.vendor.production.js",
    ["webpack.config.vendor.production.mjs"] = "webpack.config.vendor.production.mjs",
    ["webpack.config.vendor.production.cjs"] = "webpack.config.vendor.production.cjs",
    ["webpack.config.vendor.production.ts"] = "webpack.config.vendor.production.ts",
    ["webpack.config.vendor.production.mts"] = "webpack.config.vendor.production.mts",
    ["webpack.config.vendor.production.cts"] = "webpack.config.vendor.production.cts",
    ["webpack.config.vendor.js"] = "webpack.config.vendor.js",
    ["webpack.config.vendor.mjs"] = "webpack.config.vendor.mjs",
    ["webpack.config.vendor.cjs"] = "webpack.config.vendor.cjs",
    ["webpack.config.vendor.ts"] = "webpack.config.vendor.ts",
    ["webpack.config.vendor.mts"] = "webpack.config.vendor.mts",
    ["webpack.config.vendor.cts"] = "webpack.config.vendor.cts",
    ["webpack.config.js"] = "webpack.config.js",
    ["webpack.config.mjs"] = "webpack.config.mjs",
    ["webpack.config.cjs"] = "webpack.config.cjs",
    ["webpack.config.ts"] = "webpack.config.ts",
    ["webpack.config.mts"] = "webpack.config.mts",
    ["webpack.config.cts"] = "webpack.config.cts",
    ["webpack.dev.js"] = "webpack.dev.js",
    ["webpack.dev.mjs"] = "webpack.dev.mjs",
    ["webpack.dev.cjs"] = "webpack.dev.cjs",
    ["webpack.dev.ts"] = "webpack.dev.ts",
    ["webpack.dev.mts"] = "webpack.dev.mts",
    ["webpack.dev.cts"] = "webpack.dev.cts",
    ["webpack.development.js"] = "webpack.development.js",
    ["webpack.development.mjs"] = "webpack.development.mjs",
    ["webpack.development.cjs"] = "webpack.development.cjs",
    ["webpack.development.ts"] = "webpack.development.ts",
    ["webpack.development.mts"] = "webpack.development.mts",
    ["webpack.development.cts"] = "webpack.development.cts",
    ["webpack.dist.js"] = "webpack.dist.js",
    ["webpack.dist.mjs"] = "webpack.dist.mjs",
    ["webpack.dist.cjs"] = "webpack.dist.cjs",
    ["webpack.dist.ts"] = "webpack.dist.ts",
    ["webpack.dist.mts"] = "webpack.dist.mts",
    ["webpack.dist.cts"] = "webpack.dist.cts",
    ["webpack.mix.js"] = "webpack.mix.js",
    ["webpack.mix.mjs"] = "webpack.mix.mjs",
    ["webpack.mix.cjs"] = "webpack.mix.cjs",
    ["webpack.mix.ts"] = "webpack.mix.ts",
    ["webpack.mix.mts"] = "webpack.mix.mts",
    ["webpack.mix.cts"] = "webpack.mix.cts",
    ["webpack.prod.config.js"] = "webpack.prod.config.js",
    ["webpack.prod.config.mjs"] = "webpack.prod.config.mjs",
    ["webpack.prod.config.cjs"] = "webpack.prod.config.cjs",
    ["webpack.prod.config.ts"] = "webpack.prod.config.ts",
    ["webpack.prod.config.mts"] = "webpack.prod.config.mts",
    ["webpack.prod.config.cts"] = "webpack.prod.config.cts",
    ["webpack.prod.js"] = "webpack.prod.js",
    ["webpack.prod.mjs"] = "webpack.prod.mjs",
    ["webpack.prod.cjs"] = "webpack.prod.cjs",
    ["webpack.prod.ts"] = "webpack.prod.ts",
    ["webpack.prod.mts"] = "webpack.prod.mts",
    ["webpack.prod.cts"] = "webpack.prod.cts",
    ["webpack.production.js"] = "webpack.production.js",
    ["webpack.production.mjs"] = "webpack.production.mjs",
    ["webpack.production.cjs"] = "webpack.production.cjs",
    ["webpack.production.ts"] = "webpack.production.ts",
    ["webpack.production.mts"] = "webpack.production.mts",
    ["webpack.production.cts"] = "webpack.production.cts",
    ["webpack.server.js"] = "webpack.server.js",
    ["webpack.server.mjs"] = "webpack.server.mjs",
    ["webpack.server.cjs"] = "webpack.server.cjs",
    ["webpack.server.ts"] = "webpack.server.ts",
    ["webpack.server.mts"] = "webpack.server.mts",
    ["webpack.server.cts"] = "webpack.server.cts",
    ["webpack.test.js"] = "webpack.test.js",
    ["webpack.test.mjs"] = "webpack.test.mjs",
    ["webpack.test.cjs"] = "webpack.test.cjs",
    ["webpack.test.ts"] = "webpack.test.ts",
    ["webpack.test.mts"] = "webpack.test.mts",
    ["webpack.test.cts"] = "webpack.test.cts",
    ["webpack.js"] = "webpack.js",
    ["webpack.mjs"] = "webpack.mjs",
    ["webpack.cjs"] = "webpack.cjs",
    ["webpack.ts"] = "webpack.ts",
    ["webpack.mts"] = "webpack.mts",
    ["webpack.cts"] = "webpack.cts",
    ["webpackfile.js"] = "webpackfile.js",
    ["webpackfile.mjs"] = "webpackfile.mjs",
    ["webpackfile.cjs"] = "webpackfile.cjs",
    ["webpackfile.ts"] = "webpackfile.ts",
    ["webpackfile.mts"] = "webpackfile.mts",
    ["webpackfile.cts"] = "webpackfile.cts",
    ["webpack.config.coffee"] = "webpack.config.coffee",
    ["windi"] = "windi",
    ["windi.config.js"] = "windi.config.js",
    ["windi.config.cjs"] = "windi.config.cjs",
    ["windi.config.ts"] = "windi.config.ts",
    ["windi.config.cts"] = "windi.config.cts",
    ["windi.config.json"] = "windi.config.json",
    ["doc"] = "doc",
    ["docx"] = "docx",
    ["rtf"] = "rtf",
    ["odt"] = "odt",
    ["xaml"] = "xaml",
    ["xml"] = "xml",
    ["plist"] = "plist",
    ["xsd"] = "xsd",
    ["dtd"] = "dtd",
    ["xsl"] = "xsl",
    ["xslt"] = "xslt",
    ["resx"] = "resx",
    ["iml"] = "iml",
    ["xquery"] = "xquery",
    ["tmLanguage"] = "tmLanguage",
    ["manifest"] = "manifest",
    ["project"] = "project",
    ["xml.dist"] = "xml.dist",
    ["xml.dist.sample"] = "xml.dist.sample",
    ["dmn"] = "dmn",
    ["jrxml"] = "jrxml",
    ["yml.dist"] = "yml.dist",
    ["yaml.dist"] = "yaml.dist",
    ["YAML-tmLanguage"] = "YAML-tmLanguage",
    ["yang"] = "yang",
    [".yarnrc"] = ".yarnrc",
    ["yarn.lock"] = "yarn.lock",
    [".yarnclean"] = ".yarnclean",
    [".yarn-integrity"] = ".yarn-integrity",
    [".yarnrc.yml"] = ".yarnrc.yml",
    [".yarnrc.yaml"] = ".yarnrc.yaml",
    ["yarn-error.log"] = "yarn-error.log",
    ["zig"] = "zig",
    ["zon"] = "zon",
    ["zip"] = "zip",
    ["tar"] = "tar",
    ["gz"] = "gz",
    ["xz"] = "xz",
    ["lzma"] = "lzma",
    ["lz4"] = "lz4",
    ["br"] = "br",
    ["bz2"] = "bz2",
    ["bzip2"] = "bzip2",
    ["gzip"] = "gzip",
    ["brotli"] = "brotli",
    ["7z"] = "7z",
    ["rar"] = "rar",
    ["tz"] = "tz",
    ["txz"] = "txz",
    ["tgz"] = "tgz",
    ["zst"] = "zst",
}

local function get_highlight_name(data)
    if not global_opts.color_icons then
        data = default_icon
    end

    return data.name and "DevIcon" .. data.name
end

local nvim_set_hl = vim.api.nvim_set_hl
local function set_up_highlight(icon_data)
    if not global_opts.color_icons then
        icon_data = default_icon
    end

    local hl_group = get_highlight_name(icon_data)
    if hl_group and (icon_data.color or icon_data.cterm_color) then
        nvim_set_hl(0, get_highlight_name(icon_data), {
            fg = icon_data.color,
            ctermfg = tonumber(icon_data.cterm_color),
        })
    end
end

local nvim_get_hl_by_name = vim.api.nvim_get_hl_by_name
local function highlight_exists(group)
    if not group then
        return
    end

    local ok, hl = pcall(nvim_get_hl_by_name, group, true)
    return ok and not (hl or {})[true]
end

function M.set_up_highlights(allow_override)
    if not global_opts.color_icons then
        set_up_highlight(default_icon)
        return
    end

    for _, icon_data in pairs(icons) do
        local has_color = icon_data.color or icon_data.cterm_color
        local name_valid = icon_data.name
        local defined_before = highlight_exists(get_highlight_name(icon_data))
        if has_color and name_valid and (allow_override or not defined_before) then
            set_up_highlight(icon_data)
        end
    end
end

local function get_highlight_foreground(icon_data)
    if not global_opts.color_icons then
        icon_data = default_icon
    end

    return string.format("#%06x", nvim_get_hl_by_name(get_highlight_name(icon_data), true).foreground)
end

local function get_highlight_ctermfg(icon_data)
    if not global_opts.color_icons then
        icon_data = default_icon
    end

    return nvim_get_hl_by_name(get_highlight_name(icon_data), false).foreground
end

local loaded = false

function M.has_loaded()
    return loaded
end

local if_nil = vim.F.if_nil
function M.setup(opts)
    if loaded then
        return
    end

    loaded = true

    local user_icons = opts or {}

    if user_icons.default then
        global_opts.default = true
    end

    if user_icons.strict then
        global_opts.strict = true
    end

    global_opts.color_icons = if_nil(user_icons.color_icons, global_opts.color_icons)

    if user_icons.override and user_icons.override.default_icon then
        default_icon = user_icons.override.default_icon
    end

    local user_filename_icons = user_icons.override_by_filename
    local user_file_ext_icons = user_icons.override_by_extension
    local user_operating_system_icons = user_icons.override_by_operating_system
    local user_desktop_environment_icons = user_icons.override_by_desktop_environment
    local user_window_manager_icons = user_icons.override_by_window_manager

    icons = vim.tbl_extend(
        "force",
        icons,
        user_icons.override or {},
        user_filename_icons or {},
        user_file_ext_icons or {},
        user_operating_system_icons or {},
        user_desktop_environment_icons or {},
        user_window_manager_icons or {}
    )
    global_opts.override = vim.tbl_extend(
        "force",
        global_opts.override,
        user_icons.override or {},
        user_filename_icons or {},
        user_file_ext_icons or {},
        user_operating_system_icons or {},
        user_desktop_environment_icons or {},
        user_window_manager_icons or {}
    )

    if user_filename_icons then
        icons_by_filename = vim.tbl_extend("force", icons_by_filename, user_filename_icons)
    end
    if user_file_ext_icons then
        icons_by_file_extension = vim.tbl_extend("force", icons_by_file_extension, user_file_ext_icons)
    end
    if user_operating_system_icons then
        icons_by_operating_system = vim.tbl_extend("force", icons_by_operating_system, user_operating_system_icons)
    end
    if user_desktop_environment_icons then
        icons_by_desktop_environment =
            vim.tbl_extend("force", icons_by_desktop_environment, user_desktop_environment_icons)
    end
    if user_window_manager_icons then
        icons_by_window_manager = vim.tbl_extend("force", icons_by_window_manager, user_window_manager_icons)
    end

    icons[1] = default_icon

    M.set_up_highlights()

    vim.api.nvim_create_autocmd("ColorScheme", {
        desc = "Re-apply icon colors after changing colorschemes",
        group = vim.api.nvim_create_augroup("NvimWebDevicons", { clear = true }),
        callback = M.set_up_highlights,
    })

    -- highlight test command
    vim.api.nvim_create_user_command("NvimWebDeviconsHiTest", function()
        require("nvim-web-devicons.hi-test")(
            default_icon,
            global_opts.override,
            icons_by_filename,
            icons_by_file_extension,
            icons_by_operating_system,
            icons_by_desktop_environment,
            icons_by_window_manager
        )
    end, {
        desc = "nvim-web-devicons: highlight test",
    })
end

function M.get_default_icon()
    return default_icon
end

-- recursively iterate over each segment separated by '.' to parse extension with multiple dots in filename
local function iterate_multi_dotted_extension(name, icon_table)
    if name == nil then
        return nil
    end

    local compound_ext = name:match("%.(.*)")
    local icon = icon_table[compound_ext]
    if icon then
        return icon
    end

    return iterate_multi_dotted_extension(compound_ext, icon_table)
end

local function get_icon_by_extension(name, ext, opts)
    local is_strict = if_nil(opts and opts.strict, global_opts.strict)
    local icon_table = is_strict and icons_by_file_extension or icons

    if ext ~= nil then
        return icon_table[ext]
    end

    return iterate_multi_dotted_extension(name, icon_table)
end

local function get_icon_data(name, ext, opts)
    if type(name) == "string" then
        name = name:lower()
    end

    if not loaded then
        M.setup()
    end

    local has_default = if_nil(opts and opts.default, global_opts.default)
    local is_strict = if_nil(opts and opts.strict, global_opts.strict)
    local icon_data
    if is_strict then
        icon_data = icons_by_filename[name] or get_icon_by_extension(name, ext, opts) or (has_default and default_icon)
    else
        icon_data = icons[name] or get_icon_by_extension(name, ext, opts) or (has_default and default_icon)
    end

    return icon_data
end

function M.get_icon(name, ext, opts)
    local icon_data = get_icon_data(name, ext, opts)

    if icon_data then
        return icon_data.icon, get_highlight_name(icon_data)
    end
end

function M.get_icon_name_by_filetype(ft)
    return filetypes[ft]
end

function M.get_icon_by_filetype(ft, opts)
    local name = M.get_icon_name_by_filetype(ft)
    opts = opts or {}
    opts.strict = false
    return M.get_icon(name or "", nil, opts)
end

function M.get_icon_colors(name, ext, opts)
    local icon_data = get_icon_data(name, ext, opts)

    if icon_data then
        local color = icon_data.color
        local cterm_color = icon_data.cterm_color
        if icon_data.name and highlight_exists(get_highlight_name(icon_data)) then
            color = get_highlight_foreground(icon_data) or color
            cterm_color = get_highlight_ctermfg(icon_data) or cterm_color
        end
        return icon_data.icon, color, cterm_color
    end
end

function M.get_icon_colors_by_filetype(ft, opts)
    local name = M.get_icon_name_by_filetype(ft)
    return M.get_icon_colors(name or "", nil, opts)
end

function M.get_icon_color(name, ext, opts)
    local data = { M.get_icon_colors(name, ext, opts) }
    return data[1], data[2]
end

function M.get_icon_color_by_filetype(ft, opts)
    local name = M.get_icon_name_by_filetype(ft)
    opts = opts or {}
    opts.strict = false
    return M.get_icon_color(name or "", nil, opts)
end

function M.get_icon_cterm_color(name, ext, opts)
    local data = { M.get_icon_colors(name, ext, opts) }
    return data[1], data[3]
end

function M.get_icon_cterm_color_by_filetype(ft, opts)
    local name = M.get_icon_name_by_filetype(ft)
    return M.get_icon_cterm_color(name or "", nil, opts)
end

function M.set_icon(user_icons)
    icons = vim.tbl_extend("force", icons, user_icons or {})
    global_opts.override = vim.tbl_extend("force", global_opts.override, user_icons or {})
    if not global_opts.color_icons then
        return
    end

    for _, icon_data in pairs(user_icons) do
        set_up_highlight(icon_data)
    end
end

function M.set_icon_by_filetype(user_filetypes)
    filetypes = vim.tbl_extend("force", filetypes, user_filetypes or {})
end

function M.set_default_icon(icon, color, cterm_color)
    default_icon.icon = icon
    default_icon.color = color
    default_icon.cterm_color = cterm_color
    set_up_highlight(default_icon)
end

-- Load the icons already, the loaded tables depend on the 'background' setting.
refresh_icons()

function M.refresh()
    refresh_icons()
    M.set_up_highlights(true)
end

-- Change icon set on background change
vim.api.nvim_create_autocmd("OptionSet", {
    pattern = "background",
    callback = M.refresh,
})

return M
