return {
	["ai"] = {
		icon = "",
		color = "#ffb74d",
		cterm_color = "215",
		name = "ai",
	},
	["ait"] = {
		icon = "",
		color = "#ffb74d",
		cterm_color = "95",
		name = "ait",
	},
	["haxe"] = {
		icon = "",
		color = "#fc8d00",
		cterm_color = "208",
		name = "haxe",
	},
	["hxml"] = {
		icon = "",
		color = "#fc8d00",
		cterm_color = "208",
		name = "hxml",
	},
	["alloy"] = {
		icon = "",
		color = "#ff6f00",
		cterm_color = "208",
		name = "alloy",
	},
	["apex"] = {
		icon = "󰢎",
		color = "#009ce5",
		cterm_color = "38",
		name = "apex",
	},
	["duc"] = {
		icon = "󰇥",
		color = "#ff5252",
		cterm_color = "203",
		name = "duc",
	},
	["duc.fbs"] = {
		icon = "󰇥",
		color = "#ff5252",
		cterm_color = "203",
		name = "duc.fbs",
	},
	["svelte.js"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "svelte.js",
	},
	["svelte.ts"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "svelte.ts",
	},
	["iuml"] = {
		icon = "",
		color = "#f06293",
		cterm_color = "204",
		name = "svelte.ts",
	},
	["pu"] = {
		icon = "",
		color = "#f06293",
		cterm_color = "204",
		name = "svelte.ts",
	},
	["puml"] = {
		icon = "",
		color = "#f06293",
		cterm_color = "204",
		name = "svelte.ts",
	},
	["plantuml"] = {
		icon = "",
		color = "#f06293",
		cterm_color = "204",
		name = "svelte.ts",
	},
	["wsd"] = {
		icon = "",
		color = "#f06293",
		cterm_color = "204",
		name = "svelte.ts",
	},
	["stories.js"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "stories.js",
	},
	["stories.jsx"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "stories.jsx",
	},
	["stories.mdx"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "stories.mdx",
	},
	["story.js"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "story.js",
	},
	["story.jsx"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "story.jsx",
	},
	["stories.ts"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "stories.ts",
	},
	["stories.tsx"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "stories.tsx",
	},
	["story.ts"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "story.ts",
	},
	["story.tsx"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "story.tsx",
	},
	["stories.svelte"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "stories.svelte",
	},
	["story.mdx"] = {
		icon = "",
		color = "#ff4082",
		cterm_color = "204",
		name = "story.mdx",
	},
	["azure-pipelines.yml"] = {
		icon = "󱓞",
		color = "#2088e5",
		cterm_color = "32",
		name = "azure-pipelines.yml",
	},
	["azure-pipelines.yaml"] = {
		icon = "󱓞",
		color = "#2088e5",
		cterm_color = "32",
		name = "azure-pipelines.yaml",
	},
	["azure-pipelines-main.yml"] = {
		icon = "󱓞",
		color = "#2088e5",
		cterm_color = "32",
		name = "azure-pipelines-main.yml",
	},
	["azure-pipelines-main.yaml"] = {
		icon = "󱓞",
		color = "#2088e5",
		cterm_color = "32",
		name = "azure-pipelines-main.yaml",
	},
	["cmake"] = {
		icon = "",
		color = "#e63936",
		cterm_color = "196",
		name = "cmake",
	},
	["lrc"] = {
		icon = "󰈣",
		color = "#4fc6ef",
		cterm_color = "81",
		name = "lrc",
	},
	["feature"] = {
		icon = "",
		color = "#4caf51",
		cterm_color = "71",
		name = "feature",
	},
	["features"] = {
		icon = "",
		color = "#4caf51",
		cterm_color = "71",
		name = "features",
	},
	["gnu"] = {
		icon = "󰄪",
		color = "#2088e5",
		cterm_color = "33",
		name = "gnu",
	},
	["glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "glsl",
	},
	["vert"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "vert",
	},
	["tesc"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "tesc",
	},
	["tese"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "tese",
	},
	["geom"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "geom",
	},
	["frag"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "frag",
	},
	["comp"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "comp",
	},
	["vert.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "vert.glsl",
	},
	["tesc.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "tesc.glsl",
	},
	["tese.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "tese.glsl",
	},
	["geom.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "geom.glsl",
	},
	["frag.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "frag.glsl",
	},
	["comp.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "comp.glsl",
	},
	["vertex.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "vertex.glsl",
	},
	["geometry.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "geometry.glsl",
	},
	["fragment.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "fragment.glsl",
	},
	["compute.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "compute.glsl",
	},
	["ts.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "ts.glsl",
	},
	["gs.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "gs.glsl",
	},
	["vs.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "vs.glsl",
	},
	["fs.glsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "fs.glsl",
	},
	["shader"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "shader",
	},
	["vertexshader"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "vertexshader",
	},
	["fragmentshader"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "fragmentshader",
	},
	["geometryshader"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "geometryshader",
	},
	["computeshader"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "computeshader",
	},
	["hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "hlsl",
	},
	["pixel.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "pixel.hlsl",
	},
	["geometry.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "geometry.hlsl",
	},
	["compute.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "compute.hlsl",
	},
	["tessellation.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "tessellation.hlsl",
	},
	["px.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "px.hlsl",
	},
	["geom.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "geom.hlsl",
	},
	["comp.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "comp.hlsl",
	},
	["tess.hlsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "tess.hlsl",
	},
	["wgsl"] = {
		icon = "󱕅",
		color = "#ab48bd",
		cterm_color = "133",
		name = "wgsl",
	},
	["pal"] = {
		icon = "",
		color = "#4fc3f7",
		cterm_color = "81",
		name = "pal",
	},
	["gpl"] = {
		icon = "",
		color = "#4fc3f7",
		cterm_color = "81",
		name = "gpl",
	},
	["act"] = {
		icon = "",
		color = "#4fc3f7",
		cterm_color = "81",
		name = "act",
	},
	["stl"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "stl",
	},
	["stp"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "stp",
	},
	["obj"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "obj",
	},
	["o"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "o",
	},
	["ac"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "ac",
	},
	["dxf"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "dxf",
	},
	["fbx"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "fbx",
	},
	["mesh"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "mesh",
	},
	["mqo"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "mqo",
	},
	["pmd"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "pmd",
	},
	["pmx"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "pmx",
	},
	["skp"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "skp",
	},
	["vac"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "vac",
	},
	["vala"] = {
		icon = "",
		color = "#9576ce",
		cterm_color = "105",
		name = "vala",
	},
	["vdp"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "vdp",
	},
	["vox"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "vox",
	},
	["ved"] = {
		icon = "",
		color = "#ff3e00",
		cterm_color = "202",
		name = "ved",
	},
	["veda"] = {
		icon = "",
		color = "#ff3e00",
		cterm_color = "202",
		name = "veda",
	},
	["vedic"] = {
		icon = "",
		color = "#ff3e00",
		cterm_color = "202",
		name = "vedic",
	},
	["blend"] = {
		icon = "󰂫",
		color = "#ed8f30",
		cterm_color = "209",
		name = "blend",
	},
	["abc"] = {
		icon = "󰽰",
		color = "#ff5821",
		cterm_color = "202",
		name = "abc",
	},
	["accdb"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accdb",
	},
	["mdb"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "mdb",
	},
	["ada"] = {
		icon = "󱗆",
		color = "#0277bd",
		cterm_color = "31",
		name = "ada",
	},
	["adb"] = {
		icon = "󱗆",
		color = "#0277bd",
		cterm_color = "31",
		name = "adb",
	},
	["ads"] = {
		icon = "󱗆",
		color = "#0277bd",
		cterm_color = "31",
		name = "ads",
	},
	["ali"] = {
		icon = "󱗆",
		color = "#0277bd",
		cterm_color = "31",
		name = "ali",
	},
	["apk"] = {
		icon = "",
		color = "#8bc34a",
		cterm_color = "113",
		name = "apk",
	},
	["smali"] = {
		icon = "",
		color = "#8bc34a",
		cterm_color = "113",
		name = "smali",
	},
	["dex"] = {
		icon = "",
		color = "#8bc34a",
		cterm_color = "113",
		name = "dex",
	},
	["component.ts"] = {
		icon = "",
		color = "#1976d3",
		cterm_color = "32",
		name = "component.ts",
	},
	["component.js"] = {
		icon = "",
		color = "#1976d3",
		cterm_color = "32",
		name = "component.js",
	},
	["directive.ts"] = {
		icon = "",
		color = "#ab48bc",
		cterm_color = "133",
		name = "directive.ts",
	},
	["directive.js"] = {
		icon = "",
		color = "#ab48bc",
		cterm_color = "133",
		name = "directive.js",
	},
	["guard.ts"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "guard.ts",
	},
	["guard.js"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "guard.js",
	},
	["pipe.ts"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "pipe.ts",
	},
	["pipe.js"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "pipe.js",
	},
	["resolver.ts"] = {
		icon = "",
		color = "#ffc0cb",
		cterm_color = "218",
		name = "resolver.ts",
	},
	["resolver.js"] = {
		icon = "",
		color = "#ffc0cb",
		cterm_color = "218",
		name = "resolver.js",
	},
	["service.ts"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "service.ts",
	},
	["service.js"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "service.js",
	},
	["module.ts"] = {
		icon = "",
		color = "#e63936",
		cterm_color = "167",
		name = "module.ts",
	},
	["module.js"] = {
		icon = "",
		color = "#e63936",
		cterm_color = "167",
		name = "module.js",
	},
	["ng-template"] = {
		icon = "",
		color = "#e63936",
		cterm_color = "167",
		name = "ng-template",
	},
	["g4"] = {
		icon = "󱂚",
		color = "#f54436",
		cterm_color = "203",
		name = "g4",
	},
	["applescript"] = {
		icon = "",
		color = "#78919c",
		cterm_color = "103",
		name = "applescript",
	},
	["ipa"] = {
		icon = "",
		color = "#78919c",
		cterm_color = "103",
		name = "ipa",
	},
	["ino"] = {
		icon = "",
		color = "#01979d",
		cterm_color = "31",
		name = "ino",
	},
	["asm"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "asm",
	},
	["a51"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "a51",
	},
	["inc"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "inc",
	},
	["nasm"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "nasm",
	},
	["s"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "s",
	},
	["ms"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "ms",
	},
	["agc"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "agc",
	},
	["ags"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "ags",
	},
	["aea"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "aea",
	},
	["argus"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "argus",
	},
	["mitigus"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "mitigus",
	},
	["binsource"] = {
		icon = "󰘨",
		color = "#ff6e41",
		cterm_color = "203",
		name = "binsource",
	},
	["astro"] = {
		icon = "",
		color = "#ff6d00",
		cterm_color = "202",
		name = "astro",
	},
	["mp3"] = {
		icon = "󰎆",
		color = "#ee534f",
		cterm_color = "203",
		name = "mp3",
	},
	["flac"] = {
		icon = "󰎆",
		color = "#ee534f",
		cterm_color = "203",
		name = "flac",
	},
	["m4a"] = {
		icon = "󰎆",
		color = "#ee534f",
		cterm_color = "203",
		name = "m4a",
	},
	["wma"] = {
		icon = "󰎆",
		color = "#ee534f",
		cterm_color = "203",
		name = "wma",
	},
	["aiff"] = {
		icon = "󰎆",
		color = "#ee534f",
		cterm_color = "203",
		name = "aiff",
	},
	["wav"] = {
		icon = "󰎆",
		color = "#76b900",
		cterm_color = "106",
		name = "wav",
	},
	["ahk"] = {
		icon = "",
		color = "#4caf51",
		cterm_color = "71",
		name = "ahk",
	},
	["azcli"] = {
		icon = "",
		color = "#2088e5",
		cterm_color = "32",
		name = "azcli",
	},
	["bzl"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "bzl",
	},
	["bazel"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "bazel",
	},
	["bicep"] = {
		icon = "󰿗",
		color = "#fbc02d",
		cterm_color = "214",
		name = "bicep",
	},
	["b"] = {
		icon = "󰧑",
		color = "#ff4081",
		cterm_color = "204",
		name = "b",
	},
	["bf"] = {
		icon = "󰧑",
		color = "#ff4081",
		cterm_color = "204",
		name = "bf",
	},
	["c"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "c",
	},
	["i"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "i",
	},
	["mi"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "mi",
	},
	["m"] = {
		icon = "",
		color = "#ff6f00",
		cterm_color = "208",
		name = "m",
	},
	["cake"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "cake",
	},
	["cer"] = {
		icon = "󰄤",
		color = "#ff5821",
		cterm_color = "202",
		name = "cer",
	},
	["cert"] = {
		icon = "󰄤",
		color = "#ff5821",
		cterm_color = "202",
		name = "cert",
	},
	["crt"] = {
		icon = "󰄤",
		color = "#ff5821",
		cterm_color = "202",
		name = "crt",
	},
	["pgn"] = {
		icon = "󰡗",
		color = "#cfd8dd",
		cterm_color = "188",
		name = "pgn",
	},
	["fen"] = {
		icon = "󰡗",
		color = "#cfd8dd",
		cterm_color = "188",
		name = "fen",
	},
	["crx"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "crx",
	},
	["clj"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "clj",
	},
	["cljs"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "cljs",
	},
	["cljc"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "cljc",
	},
	["coffee"] = {
		icon = "",
		color = "#6f4e38",
		cterm_color = "239",
		name = "coffee",
	},
	["cson"] = {
		icon = "",
		color = "#6f4e38",
		cterm_color = "239",
		name = "cson",
	},
	["iced"] = {
		icon = "",
		color = "#6f4e38",
		cterm_color = "239",
		name = "iced",
	},
	["cfml"] = {
		icon = "",
		color = "#ff4081",
		cterm_color = "204",
		name = "cfml",
	},
	["cfc"] = {
		icon = "",
		color = "#ff4081",
		cterm_color = "204",
		name = "cfc",
	},
	["lucee"] = {
		icon = "",
		color = "#ff4081",
		cterm_color = "204",
		name = "lucee",
	},
	["cfm"] = {
		icon = "",
		color = "#ff4081",
		cterm_color = "204",
		name = "cfm",
	},
	["command"] = {
		icon = "󰘳",
		color = "#90a4ae",
		cterm_color = "109",
		name = "command",
	},
	["sh"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "sh",
	},
	["ksh"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "ksh",
	},
	["csh"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "csh",
	},
	["tcsh"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "tcsh",
	},
	["zsh"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "zsh",
	},
	[".zshrc"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = ".zshrc",
	},
	[".zsh_history"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = ".zsh_history",
	},
	["bat"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "bat",
	},
	["awk"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "awk",
	},
	["exp"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "exp",
	},
	["nu"] = {
		icon = "󰆍",
		color = "#ff7043",
		cterm_color = "203",
		name = "nu",
	},
	["bash"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "bash",
	},
	["cmd"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "cmd",
	},
	["fish"] = {
		icon = "󰈺",
		color = "#ff7043",
		cterm_color = "203",
		name = "fish",
	},
	["cc"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "cc",
	},
	["cpp"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "cpp",
	},
	["cxx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "cxx",
	},
	["c++"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "cpp",
	},
	["cp"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "cp",
	},
	["mii"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "mii",
	},
	["ii"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "ii",
	},
	["cr"] = {
		icon = "",
		color = "#cfd8dd",
		cterm_color = "188",
		name = "cr",
	},
	["ecr"] = {
		icon = "",
		color = "#cfd8dd",
		cterm_color = "188",
		name = "ecr",
	},
	["cs"] = {
		icon = "󰌛",
		color = "#0188d1",
		cterm_color = "32",
		name = "cs",
	},
	["csx"] = {
		icon = "󰌛",
		color = "#0188d1",
		cterm_color = "32",
		name = "csx",
	},
	["csharp"] = {
		icon = "󰌛",
		color = "#0188d1",
		cterm_color = "32",
		name = "csharp",
	},
	["css.map"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "css.map",
	},
	["css"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "css",
	},
	["d"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "d",
	},
	["freezed.dart"] = {
		icon = "",
		color = "#90a4ae",
		cterm_color = "109",
		name = "freezed.dart",
	},
	["g.dart"] = {
		icon = "",
		color = "#90a4ae",
		cterm_color = "109",
		name = "g.dart",
	},
	["dart"] = {
		icon = "",
		color = "#59b6f0",
		cterm_color = "75",
		name = "dart",
	},
	["pdb"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "pdb",
	},
	["sql"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "sql",
	},
	["pks"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "pks",
	},
	["pkb"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "pkb",
	},
	["sqlite"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "sqlite",
	},
	["sqlite3"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "sqlite3",
	},
	["pgsql"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "pgsql",
	},
	["postgres"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "postgres",
	},
	["plpgsql"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "plpgsql",
	},
	["psql"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "psql",
	},
	["db"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "db",
	},
	["db3"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "db3",
	},
	["dblite"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "dblite",
	},
	["dblite3"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "dblite3",
	},
	["debugsymbols"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "debugsymbols",
	},
	["dsc"] = {
		icon = "",
		color = "#ffd550",
		cterm_color = "221",
		name = "dsc",
	},
	["dhall"] = {
		icon = "󰴓",
		color = "#78919c",
		cterm_color = "103",
		name = "dhall",
	},
	["dhallb"] = {
		icon = "󰴓",
		color = "#78919c",
		cterm_color = "103",
		name = "dhallb",
	},
	["iso"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "iso",
	},
	["vmdk"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "vmdk",
	},
	["hdd"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "hdd",
	},
	["qcow"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "qcow",
	},
	["qcow2"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "qcow2",
	},
	["qed"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "qed",
	},
	["dmg"] = {
		icon = "",
		color = "#b1bec5",
		cterm_color = "250",
		name = "dmg",
	},
	["djt"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "djt",
	},
	["dll"] = {
		icon = "󱁼",
		color = "#42a5f5",
		cterm_color = "75",
		name = "dll",
	},
	["ilk"] = {
		icon = "󱁼",
		color = "#42a5f5",
		cterm_color = "75",
		name = "ilk",
	},
	["so"] = {
		icon = "󱁼",
		color = "#42a5f5",
		cterm_color = "75",
		name = "so",
	},
	["txt"] = {
		icon = "󰈙",
		color = "#42a5f5",
		cterm_color = "75",
		name = "txt",
	},
	["drone.yml"] = {
		icon = "󰐝",
		color = "#cfd8dd",
		cterm_color = "188",
		name = "drone.yml",
	},
	["edge"] = {
		icon = "",
		color = "#ef6c02",
		cterm_color = "202",
		name = "edge",
	},
	["ex"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "ex",
	},
	["exs"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "exs",
	},
	["eex"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "eex",
	},
	["leex"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "leex",
	},
	["heex"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "heex",
	},
	["elm"] = {
		icon = "",
		color = "#60b6cc",
		cterm_color = "74",
		name = "elm",
	},
	["ics"] = {
		icon = "󰇮",
		color = "#42a5f5",
		cterm_color = "75",
		name = "ics",
	},
	["erl"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "erl",
	},
	["exe"] = {
		icon = "",
		color = "#e64a19",
		cterm_color = "166",
		name = "exe",
	},
	["msi"] = {
		icon = "",
		color = "#e64a19",
		cterm_color = "166",
		name = "msi",
	},
	["fig"] = {
		icon = "",
		color = "#f4521e",
		cterm_color = "202",
		name = "fig",
	},
	["woff"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "woff",
	},
	["woff2"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "woff2",
	},
	["ttf"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "ttf",
	},
	["eot"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "eot",
	},
	["suit"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "suit",
	},
	["otf"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "otf",
	},
	["bmap"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "bmap",
	},
	["fnt"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "fnt",
	},
	["odttf"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "odttf",
	},
	["ttc"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "ttc",
	},
	["font"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "font",
	},
	["fonts"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "fonts",
	},
	["sui"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "sui",
	},
	["ntf"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "ntf",
	},
	["mrf"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "mrf",
	},
	["f"] = {
		icon = "󱈚",
		color = "#ff7043",
		cterm_color = "203",
		name = "f",
	},
	["f77"] = {
		icon = "󱈚",
		color = "#ff7043",
		cterm_color = "203",
		name = "f77",
	},
	["f90"] = {
		icon = "󱈚",
		color = "#ff7043",
		cterm_color = "203",
		name = "f90",
	},
	["f95"] = {
		icon = "󱈚",
		color = "#ff7043",
		cterm_color = "203",
		name = "f95",
	},
	["f03"] = {
		icon = "󱈚",
		color = "#ff7043",
		cterm_color = "203",
		name = "f03",
	},
	["f08"] = {
		icon = "󱈚",
		color = "#ff7043",
		cterm_color = "203",
		name = "f08",
	},
	["fs"] = {
		icon = "",
		color = "#31b9db",
		cterm_color = "74",
		name = "fs",
	},
	["fsx"] = {
		icon = "",
		color = "#31b9db",
		cterm_color = "74",
		name = "fsx",
	},
	["fsi"] = {
		icon = "",
		color = "#31b9db",
		cterm_color = "74",
		name = "fsi",
	},
	["fsproj"] = {
		icon = "",
		color = "#31b9db",
		cterm_color = "74",
		name = "fsproj",
	},
	["gmi"] = {
		icon = "󰖟",
		color = "#82c784",
		cterm_color = "114",
		name = "gmi",
	},
	["gemini"] = {
		icon = "󰖟",
		color = "#82c784",
		cterm_color = "114",
		name = "gemini",
	},
	["gitlab-ci.yml"] = {
		icon = "",
		color = "#e63936",
		cterm_color = "167",
		name = "gitlab-ci.yml",
	},
	["go"] = {
		icon = "󰟓",
		color = "#02acc1",
		cterm_color = "37",
		name = "go",
	},
	["godot"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "godot",
	},
	["tres"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "tres",
	},
	["tscn"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "tscn",
	},
	["gdns"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "gdns",
	},
	["gdnlib"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "gdnlib",
	},
	["gdshader"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "gdshader",
	},
	["gdshaderinc"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "gdshaderinc",
	},
	["gdextension"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "gdextension",
	},
	["gd"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "gd",
	},
	["gradle"] = {
		icon = "",
		color = "#0397a7",
		cterm_color = "31",
		name = "gradle",
	},
	["graphql"] = {
		icon = "󰡷",
		color = "#ec417a",
		cterm_color = "204",
		name = "graphql",
	},
	["gql"] = {
		icon = "󰡷",
		color = "#ec417a",
		cterm_color = "204",
		name = "gql",
	},
	["h"] = {
		icon = "󰠩",
		color = "#0188d1",
		cterm_color = "32",
		name = "h",
	},
	["haml"] = {
		icon = "",
		color = "#f4521e",
		cterm_color = "202",
		name = "haml",
	},
	["hbs"] = {
		icon = "󱗞",
		color = "#ff7043",
		cterm_color = "203",
		name = "hbs",
	},
	["mustache"] = {
		icon = "󱗞",
		color = "#ff7043",
		cterm_color = "203",
		name = "mustache",
	},
	["hs"] = {
		icon = "",
		color = "#ffa726",
		cterm_color = "214",
		name = "hs",
	},
	["hx"] = {
		icon = "",
		color = "#f68713",
		cterm_color = "208",
		name = "hx",
	},
	["dat"] = {
		icon = "󱊧",
		color = "#25a79a",
		cterm_color = "36",
		name = "dat",
	},
	["bin"] = {
		icon = "󱊧",
		color = "#25a79a",
		cterm_color = "36",
		name = "bin",
	},
	["hex"] = {
		icon = "󱊧",
		color = "#25a79a",
		cterm_color = "36",
		name = "hex",
	},
	["hh"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "hh",
	},
	["hpp"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "hpp",
	},
	["hxx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "hxx",
	},
	["h++"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "hpp",
	},
	["hp"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "hp",
	},
	["tcc"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "tcc",
	},
	["inl"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "inl",
	},
	["htm"] = {
		icon = "",
		color = "#e44e27",
		cterm_color = "166",
		name = "htm",
	},
	["xhtml"] = {
		icon = "",
		color = "#e44e27",
		cterm_color = "166",
		name = "xhtml",
	},
	["html_vm"] = {
		icon = "",
		color = "#e44e27",
		cterm_color = "166",
		name = "html_vm",
	},
	["asp"] = {
		icon = "",
		color = "#e44e27",
		cterm_color = "166",
		name = "asp",
	},
	["http"] = {
		icon = "󰖟",
		color = "#e63936",
		cterm_color = "167",
		name = "http",
	},
	["rest"] = {
		icon = "󰖟",
		color = "#e63936",
		cterm_color = "167",
		name = "rest",
	},
	["huff"] = {
		icon = "",
		color = "#cfd8dd",
		cterm_color = "188",
		name = "huff",
	},
	["pot"] = {
		icon = "󰗊",
		color = "#7986cb",
		cterm_color = "104",
		name = "pot",
	},
	["po"] = {
		icon = "󰗊",
		color = "#7986cb",
		cterm_color = "104",
		name = "po",
	},
	["mo"] = {
		icon = "󰗊",
		color = "#7986cb",
		cterm_color = "104",
		name = "mo",
	},
	["lang"] = {
		icon = "󰗊",
		color = "#7986cb",
		cterm_color = "104",
		name = "lang",
	},
	["idr"] = {
		icon = "󰛓",
		color = "#f54436",
		cterm_color = "203",
		name = "idr",
	},
	["ibc"] = {
		icon = "󰛓",
		color = "#f54436",
		cterm_color = "203",
		name = "ibc",
	},
	["png"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "png",
	},
	["jpeg"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jpeg",
	},
	["jpg"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jpg",
	},
	["gif"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "gif",
	},
	["ico"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "ico",
	},
	["tif"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "tif",
	},
	["tiff"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "tiff",
	},
	["psd"] = {
		icon = "",
		color = "#64b6f7",
		cterm_color = "111",
		name = "psd",
	},
	["psb"] = {
		icon = "",
		color = "#64b6f7",
		cterm_color = "111",
		name = "psb",
	},
	["psdt"] = {
		icon = "",
		color = "#64b6f7",
		cterm_color = "111",
		name = "psdt",
	},
	["ami"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "ami",
	},
	["apx"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "apx",
	},
	["avif"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "avif",
	},
	["bmp"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "bmp",
	},
	["bpg"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "bpg",
	},
	["brk"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "brk",
	},
	["cur"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "cur",
	},
	["dds"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "dds",
	},
	["dng"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "dng",
	},
	["exr"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "exr",
	},
	["fpx"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "fpx",
	},
	["gbr"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "gbr",
	},
	["img"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "img",
	},
	["jbig2"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jbig2",
	},
	["jb2"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jb2",
	},
	["jng"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jng",
	},
	["jxr"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jxr",
	},
	["pgf"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "pgf",
	},
	["pic"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "pic",
	},
	["raw"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "raw",
	},
	["webp"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "webp",
	},
	["eps"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "eps",
	},
	["afphoto"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "afphoto",
	},
	["ase"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "ase",
	},
	["aseprite"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "aseprite",
	},
	["clip"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "clip",
	},
	["cpt"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "cpt",
	},
	["heif"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "heif",
	},
	["heic"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "heic",
	},
	["kra"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "kra",
	},
	["mdp"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "mdp",
	},
	["ora"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "ora",
	},
	["pdn"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "pdn",
	},
	["reb"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "reb",
	},
	["sai"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "sai",
	},
	["tga"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "tga",
	},
	["xcf"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "xcf",
	},
	["jfif"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "jfif",
	},
	["ppm"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "ppm",
	},
	["pbm"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "pbm",
	},
	["pgm"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "pgm",
	},
	["pnm"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "pnm",
	},
	["icns"] = {
		icon = "󰈟",
		color = "#25a6a0",
		cterm_color = "37",
		name = "icns",
	},
	["jar"] = {
		icon = "󰛊",
		color = "#f54436",
		cterm_color = "203",
		name = "jar",
	},
	["java"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "java",
	},
	["jsp"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "jsp",
	},
	["class"] = {
		icon = "",
		color = "#2088e5",
		cterm_color = "32",
		name = "class",
	},
	["js.map"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "js.map",
	},
	["mjs.map"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "mjs.map",
	},
	["cjs.map"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "cjs.map",
	},
	["esx"] = {
		icon = "󰌞",
		color = "#ffca29",
		cterm_color = "220",
		name = "esx",
	},
	["mjs"] = {
		icon = "󰌞",
		color = "#ffca29",
		cterm_color = "220",
		name = "mjs",
	},
	["jenkins"] = {
		icon = "",
		color = "#f0d7b7",
		cterm_color = "223",
		name = "jenkins",
	},
	["jinja"] = {
		icon = "",
		color = "#bdbdbd",
		cterm_color = "250",
		name = "jinja",
	},
	["jinja2"] = {
		icon = "",
		color = "#bdbdbd",
		cterm_color = "250",
		name = "jinja2",
	},
	["j2"] = {
		icon = "",
		color = "#bdbdbd",
		cterm_color = "250",
		name = "j2",
	},
	["jinja-html"] = {
		icon = "",
		color = "#bdbdbd",
		cterm_color = "250",
		name = "jinja-html",
	},
	["json"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "json",
	},
	["jsonc"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "jsonc",
	},
	["tsbuildinfo"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "tsbuildinfo",
	},
	["json5"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "json5",
	},
	["jsonl"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "jsonl",
	},
	["ndjson"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "ndjson",
	},
	["jl"] = {
		icon = "",
		color = "#338a23",
		cterm_color = "64",
		name = "jl",
	},
	["ipynb"] = {
		icon = "󰠮",
		color = "#f57d01",
		cterm_color = "208",
		name = "ipynb",
	},
	["pub"] = {
		icon = "󰌆",
		color = "#25a79a",
		cterm_color = "36",
		name = "pub",
	},
	["key"] = {
		icon = "󰌆",
		color = "#25a79a",
		cterm_color = "36",
		name = "key",
	},
	["pem"] = {
		icon = "󰌆",
		color = "#25a79a",
		cterm_color = "36",
		name = "pem",
	},
	["asc"] = {
		icon = "󰌆",
		color = "#25a79a",
		cterm_color = "36",
		name = "asc",
	},
	["gpg"] = {
		icon = "󰌆",
		color = "#25a79a",
		cterm_color = "36",
		name = "gpg",
	},
	["passwd"] = {
		icon = "󰌆",
		color = "#25a79a",
		cterm_color = "36",
		name = "passwd",
	},
	["kt"] = {
		icon = "",
		color = "#1a95d9",
		cterm_color = "32",
		name = "kt",
	},
	["kts"] = {
		icon = "",
		color = "#1a95d9",
		cterm_color = "32",
		name = "kts",
	},
	["blade.php"] = {
		icon = "",
		color = "#ff5252",
		cterm_color = "203",
		name = "blade.php",
	},
	["inky.php"] = {
		icon = "",
		color = "#ff5252",
		cterm_color = "203",
		name = "inky.php",
	},
	["less"] = {
		icon = "",
		color = "#0277bd",
		cterm_color = "31",
		name = "less",
	},
	["lib"] = {
		icon = "󱔗",
		color = "#8bc34a",
		cterm_color = "113",
		name = "lib",
	},
	["bib"] = {
		icon = "󱔗",
		color = "#8bc34a",
		cterm_color = "113",
		name = "bib",
	},
	["a"] = {
		icon = "󱔗",
		color = "#8bc34a",
		cterm_color = "113",
		name = "a",
	},
	["ly"] = {
		icon = "",
		color = "#66bb6b",
		cterm_color = "71",
		name = "ly",
	},
	["liquid"] = {
		icon = "",
		color = "#2ab6f6",
		cterm_color = "39",
		name = "liquid",
	},
	["lisp"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "lisp",
	},
	["lsp"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "lsp",
	},
	["cl"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "cl",
	},
	["fast"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "fast",
	},
	["ls"] = {
		icon = "",
		color = "#317fac",
		cterm_color = "67",
		name = "ls",
	},
	["lock"] = {
		icon = "",
		color = "#ffd550",
		cterm_color = "221",
		name = "lock",
	},
	["log"] = {
		icon = "",
		color = "#afb42b",
		cterm_color = "142",
		name = "log",
	},
	["lol"] = {
		icon = "󰄛",
		color = "#ef5351",
		cterm_color = "203",
		name = "lol",
	},
	["lua"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "lua",
	},
    ["luau"] = {
        icon = "",
        color = "#007ABF",
        cterm_color = "32",
        name = "Luau",
    },

	["md"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "md",
	},
	["markdown"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "markdown",
	},
	["rst"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "rst",
	},
	["svx"] = {
		icon = "",
		color = "#ff5821",
		cterm_color = "202",
		name = "svx",
	},
	["mdx"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "mdx",
	},
	["merlin"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "merlin",
	},
	["mcfunction"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcfunction",
	},
	["mcmeta"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcmeta",
	},
	["mcr"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcr",
	},
	["mca"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mca",
	},
	["mcgame"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcgame",
	},
	["mclevel"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mclevel",
	},
	["mcworld"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcworld",
	},
	["mine"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mine",
	},
	["mus"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mus",
	},
	["mcstructure"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcstructure",
	},
	["mcpack"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcpack",
	},
	["mcaddon"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcaddon",
	},
	["mctemplate"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mctemplate",
	},
	["mcproject"] = {
		icon = "󰍳",
		color = "#4caf51",
		cterm_color = "71",
		name = "mcproject",
	},
	["mint"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "mint",
	},
	["mojo"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "mojo",
	},
	["moon"] = {
		icon = "",
		color = "#fbc02d",
		cterm_color = "214",
		name = "moon",
	},
	["mxml"] = {
		icon = "󰈮",
		color = "#ffa726",
		cterm_color = "214",
		name = "mxml",
	},
	["nginx"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "nginx",
	},
	["nginxconf"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "nginxconf",
	},
	["nginxconfig"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "nginxconfig",
	},
	["nim"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "nim",
	},
	["nimble"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "nimble",
	},
	["nix"] = {
		icon = "",
		color = "#5175c2",
		cterm_color = "67",
		name = "nix",
	},
	["njk"] = {
		icon = "",
		color = "#388e3c",
		cterm_color = "65",
		name = "njk",
	},
	["nunjucks"] = {
		icon = "",
		color = "#388e3c",
		cterm_color = "65",
		name = "nunjucks",
	},
	["ml"] = {
		icon = "",
		color = "#ff9800",
		cterm_color = "208",
		name = "ml",
	},
	["mli"] = {
		icon = "",
		color = "#ff9800",
		cterm_color = "208",
		name = "mli",
	},
	["cmx"] = {
		icon = "",
		color = "#ff9800",
		cterm_color = "208",
		name = "cmx",
	},
	["opam"] = {
		icon = "",
		color = "#ff9800",
		cterm_color = "208",
		name = "opam",
	},
	["pas"] = {
		icon = "󰏣",
		color = "#0188d1",
		cterm_color = "32",
		name = "pas",
	},
	["pwn"] = {
		icon = "󰡙",
		color = "#ef6c02",
		cterm_color = "202",
		name = "pwn",
	},
	["amx"] = {
		icon = "󰡙",
		color = "#ef6c02",
		cterm_color = "202",
		name = "amx",
	},
	["pdf"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "pdf",
	},
	["pm"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "pm",
	},
	["raku"] = {
		icon = "",
		color = "#9575ce",
		cterm_color = "104",
		name = "raku",
	},
	["pine"] = {
		icon = "󰐅",
		color = "#66bb6b",
		cterm_color = "71",
		name = "pine",
	},
	["pipeline"] = {
		icon = "",
		color = "#f57f19",
		cterm_color = "208",
		name = "pipeline",
	},
	["pkl"] = {
		icon = "",
		color = "#699f37",
		cterm_color = "71",
		name = "pkl",
	},
	["pptx"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "pptx",
	},
	["ppt"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "ppt",
	},
	["pptm"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "pptm",
	},
	["potx"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "potx",
	},
	["potm"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "potm",
	},
	["ppsx"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "ppsx",
	},
	["ppsm"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "ppsm",
	},
	["pps"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "pps",
	},
	["ppam"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "ppam",
	},
	["ppa"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "ppa",
	},
	["odp"] = {
		icon = "󰈧",
		color = "#d14525",
		cterm_color = "166",
		name = "odp",
	},
	["ps1"] = {
		icon = "󰨊",
		color = "#04a9f4",
		cterm_color = "39",
		name = "ps1",
	},
	["psm1"] = {
		icon = "󰨊",
		color = "#04a9f4",
		cterm_color = "39",
		name = "psm1",
	},
	["psd1"] = {
		icon = "󰨊",
		color = "#04a9f4",
		cterm_color = "39",
		name = "psd1",
	},
	["ps1xml"] = {
		icon = "󰨊",
		color = "#04a9f4",
		cterm_color = "39",
		name = "ps1xml",
	},
	["psc1"] = {
		icon = "󰨊",
		color = "#04a9f4",
		cterm_color = "39",
		name = "psc1",
	},
	["pssc"] = {
		icon = "󰨊",
		color = "#04a9f4",
		cterm_color = "39",
		name = "pssc",
	},
	["prisma"] = {
		icon = "",
		color = "#00bfa5",
		cterm_color = "37",
		name = "prisma",
	},
	["p"] = {
		icon = "󰏒",
		color = "#ef5351",
		cterm_color = "203",
		name = "p",
	},
	["pro"] = {
		icon = "󰏒",
		color = "#ef5351",
		cterm_color = "203",
		name = "pro",
	},
	["pl"] = {
		icon = "󰏒",
		color = "#ef5351",
		cterm_color = "203",
		name = "pl",
	},
	["jade"] = {
		icon = "",
		color = "#f0cca3",
		cterm_color = "223",
		name = "jade",
	},
	["pug"] = {
		icon = "",
		color = "#f0cca3",
		cterm_color = "223",
		name = "pug",
	},
	["pure"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "pure",
	},
	["purs"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "purs",
	},
	["py"] = {
		icon = "",
		color = "#3a87cb",
		cterm_color = "221",
		name = "py",
	},
	["r"] = {
		icon = "",
		color = "#1976d3",
		cterm_color = "32",
		name = "r",
	},
	["rmd"] = {
		icon = "",
		color = "#1976d3",
		cterm_color = "32",
		name = "rmd",
	},
	["raml"] = {
		icon = "󰘦",
		color = "#42a5f5",
		cterm_color = "75",
		name = "raml",
	},
	["cshtml"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "cshtml",
	},
	["vbhtml"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "vbhtml",
	},
	["tsx"] = {
		icon = "",
		color = "#04bcd4",
		cterm_color = "38",
		name = "tsx",
	},
	["jsx"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "jsx",
	},
	["resi"] = {
		icon = "",
		color = "#ffb300",
		cterm_color = "214",
		name = "resi",
	},
	["res"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "res",
	},
	["robot"] = {
		icon = "󱙺",
		color = "#00bfa5",
		cterm_color = "37",
		name = "robot",
	},
	["routing.ts"] = {
		icon = "󰑪",
		color = "#44a047",
		cterm_color = "71",
		name = "routing.ts",
	},
	["routing.tsx"] = {
		icon = "󰑪",
		color = "#44a047",
		cterm_color = "71",
		name = "routing.tsx",
	},
	["routing.js"] = {
		icon = "󰑪",
		color = "#44a047",
		cterm_color = "71",
		name = "routing.js",
	},
	["routing.jsx"] = {
		icon = "󰑪",
		color = "#44a047",
		cterm_color = "71",
		name = "routing.jsx",
	},
	["rb"] = {
		icon = "󰴭",
		color = "#f54436",
		cterm_color = "203",
		name = "rb",
	},
	["erb"] = {
		icon = "󰴭",
		color = "#f54436",
		cterm_color = "203",
		name = "erb",
	},
	["rbs"] = {
		icon = "󰴭",
		color = "#f54436",
		cterm_color = "203",
		name = "rbs",
	},
	["rs"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "rs",
	},
	["ron"] = {
		icon = "",
		color = "#ff7043",
		cterm_color = "203",
		name = "ron",
	},
	["scss"] = {
		icon = "",
		color = "#ec417a",
		cterm_color = "204",
		name = "scss",
	},
	["sass"] = {
		icon = "",
		color = "#ec417a",
		cterm_color = "204",
		name = "sass",
	},
	["sbt"] = {
		icon = "",
		color = "#0277bd",
		cterm_color = "31",
		name = "sbt",
	},
	["scala"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "scala",
	},
	["sc"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "sc",
	},
	["ss"] = {
		icon = "󰘧",
		color = "#f54436",
		cterm_color = "203",
		name = "ss",
	},
	["scm"] = {
		icon = "󰘧",
		color = "#f54436",
		cterm_color = "203",
		name = "scm",
	},
	["code-search"] = {
		icon = "󰱼",
		color = "#42a5f5",
		cterm_color = "75",
		name = "code-search",
	},
	["ini"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "ini",
	},
	["dlc"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "dlc",
	},
	["config"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "config",
	},
	["conf"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "conf",
	},
	["properties"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "properties",
	},
	["prop"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "prop",
	},
	["settings"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "settings",
	},
	["option"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "option",
	},
	["props"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "props",
	},
	["toml"] = {
		icon = "",
		color = "#ef5351",
		cterm_color = "203",
		name = "toml",
	},
	["prefs"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "prefs",
	},
	["sln.dotsettings"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "sln.dotsettings",
	},
	["sln.dotsettings.user"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "sln.dotsettings.user",
	},
	["cfg"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "cfg",
	},
	["unity"] = {
		icon = "󰚯",
		color = "#1976d3",
		cterm_color = "32",
		name = "unity",
	},
	["sketch"] = {
		icon = "󰇈",
		color = "#ffc107",
		cterm_color = "214",
		name = "sketch",
	},
	["slim"] = {
		icon = "",
		color = "#f57f19",
		cterm_color = "208",
		name = "slim",
	},
	["tpl"] = {
		icon = "",
		color = "#ffcf03",
		cterm_color = "220",
		name = "tpl",
	},
	["sol"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "sol",
	},
	["styl"] = {
		icon = "",
		color = "#c0ca33",
		cterm_color = "149",
		name = "styl",
	},
	["srt"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "srt",
	},
	["ssa"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "ssa",
	},
	["ttml"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "ttml",
	},
	["sbv"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "sbv",
	},
	["dfxp"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "dfxp",
	},
	["vtt"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "vtt",
	},
	["sub"] = {
		icon = "󰨖",
		color = "#ff9800",
		cterm_color = "208",
		name = "sub",
	},
	["sublime-project"] = {
		icon = "",
		color = "#ffb74d",
		cterm_color = "215",
		name = "sublime-project",
	},
	["sublime-workspace"] = {
		icon = "",
		color = "#ffb74d",
		cterm_color = "215",
		name = "sublime-workspace",
	},
	["svelte"] = {
		icon = "",
		color = "#ff5821",
		cterm_color = "202",
		name = "svelte",
	},
	["svg"] = {
		icon = "󰜡",
		color = "#ffb300",
		cterm_color = "214",
		name = "svg",
	},
	["swift"] = {
		icon = "󰛥",
		color = "#fe5e2f",
		cterm_color = "202",
		name = "swift",
	},
	["xlsx"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xlsx",
	},
	["xlsm"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xlsm",
	},
	["xls"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xls",
	},
	["csv"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "csv",
	},
	["tsv"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "tsv",
	},
	["psv"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "psv",
	},
	["ods"] = {
		icon = "󰈛",
		color = "#8bc34a",
		cterm_color = "113",
		name = "ods",
	},
	["tcl"] = {
		icon = "󰛓",
		color = "#ef5351",
		cterm_color = "203",
		name = "tcl",
	},
	["templ"] = {
		icon = "󰗀",
		color = "#ffd550",
		cterm_color = "221",
		name = "templ",
	},
	["template"] = {
		icon = "󰘓",
		color = "#90a4ae",
		cterm_color = "109",
		name = "template",
	},
	["tf"] = {
		icon = "",
		color = "#5d6bc0",
		cterm_color = "61",
		name = "tf",
	},
	["tf.json"] = {
		icon = "",
		color = "#5d6bc0",
		cterm_color = "61",
		name = "tf.json",
	},
	["tfvars"] = {
		icon = "",
		color = "#5d6bc0",
		cterm_color = "61",
		name = "tfvars",
	},
	["tfstate"] = {
		icon = "",
		color = "#5d6bc0",
		cterm_color = "61",
		name = "tfstate",
	},
	["tfbackend"] = {
		icon = "",
		color = "#5d6bc0",
		cterm_color = "61",
		name = "tfbackend",
	},
	["spec.js"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "spec.js",
	},
	["spec.cjs"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "spec.cjs",
	},
	["spec.mjs"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "spec.mjs",
	},
	["e2e-spec.js"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "e2e-spec.js",
	},
	["e2e-spec.cjs"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "e2e-spec.cjs",
	},
	["e2e-spec.mjs"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "e2e-spec.mjs",
	},
	["test.js"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "test.js",
	},
	["test.cjs"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "test.cjs",
	},
	["test.mjs"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "test.mjs",
	},
	["js.snap"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "js.snap",
	},
	["cy.js"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "cy.js",
	},
	["spec.jsx"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "spec.jsx",
	},
	["test.jsx"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "test.jsx",
	},
	["jsx.snap"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "jsx.snap",
	},
	["cy.jsx"] = {
		icon = "",
		color = "#ffca29",
		cterm_color = "220",
		name = "cy.jsx",
	},
	["spec.tsx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "spec.tsx",
	},
	["test.ts"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "test.ts",
	},
	["test.tsx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "test.tsx",
	},
	["tsx.snap"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "tsx.snap",
	},
	["cy.tsx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "cy.tsx",
	},
	["spec-d.tsx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "spec-d.tsx",
	},
	["test-d.tsx"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "test-d.tsx",
	},
	["tex"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "tex",
	},
	["sty"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "sty",
	},
	["dtx"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "dtx",
	},
	["ltx"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "ltx",
	},
	["todo"] = {
		icon = "",
		color = "#7cb442",
		cterm_color = "107",
		name = "todo",
	},
	["tree"] = {
		icon = "󰙅",
		color = "#7cb442",
		cterm_color = "107",
		name = "tree",
	},
	["d.ts"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "d.ts",
	},
	["d.cts"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "d.cts",
	},
	["d.mts"] = {
		icon = "",
		color = "#0188d1",
		cterm_color = "32",
		name = "d.mts",
	},
	["twig"] = {
		icon = "",
		color = "#9bb92f",
		cterm_color = "142",
		name = "twig",
	},
	["url"] = {
		icon = "󰌹",
		color = "#42a5f5",
		cterm_color = "75",
		name = "url",
	},
	["vhd"] = {
		icon = "󰍛",
		color = "#ff7043",
		cterm_color = "203",
		name = "vhd",
	},
	["sv"] = {
		icon = "󰍛",
		color = "#ff7043",
		cterm_color = "203",
		name = "sv",
	},
	["svh"] = {
		icon = "󰍛",
		color = "#ff7043",
		cterm_color = "203",
		name = "svh",
	},
	["webm"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "webm",
	},
	["mkv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mkv",
	},
	["flv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "flv",
	},
	["vob"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "vob",
	},
	["ogv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "ogv",
	},
	["ogg"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "ogg",
	},
	["gifv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "gifv",
	},
	["avi"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "avi",
	},
	["mov"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mov",
	},
	["qt"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "qt",
	},
	["wmv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "wmv",
	},
	["yuv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "yuv",
	},
	["rm"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "rm",
	},
	["rmvb"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "rmvb",
	},
	["mp4"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mp4",
	},
	["m4v"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "m4v",
	},
	["mpg"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mpg",
	},
	["mp2"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mp2",
	},
	["mpeg"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mpeg",
	},
	["mpe"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mpe",
	},
	["mpv"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "mpv",
	},
	["m2v"] = {
		icon = "󰎁",
		color = "#ff9800",
		cterm_color = "208",
		name = "m2v",
	},
	["vimrc"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "vimrc",
	},
	["gvimrc"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "gvimrc",
	},
	["exrc"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "exrc",
	},
	["vim"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "vim",
	},
	["viminfo"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "viminfo",
	},
	["vdi"] = {
		icon = "󰌢",
		color = "#009ce5",
		cterm_color = "38",
		name = "vdi",
	},
	["vbox"] = {
		icon = "󰌢",
		color = "#009ce5",
		cterm_color = "38",
		name = "vbox",
	},
	["vbox-prev"] = {
		icon = "󰌢",
		color = "#009ce5",
		cterm_color = "38",
		name = "vbox-prev",
	},
	["csproj"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "csproj",
	},
	["ruleset"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "ruleset",
	},
	["sln"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "sln",
	},
	["slnx"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "slnx",
	},
	["suo"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "suo",
	},
	["swagger.json"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "swagger.json",
	},
	["swagger.yml"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "swagger.yml",
	},
	["swagger.yaml"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "swagger.yaml",
	},
	["vb"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "vb",
	},
	["vbs"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "vbs",
	},
	["vcxitems"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "vcxitems",
	},
	["vcxitems.filters"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "vcxitems.filters",
	},
	["vcxproj"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "vcxproj",
	},
	["vcxproj.filters"] = {
		icon = "󰘐",
		color = "#ab48bc",
		cterm_color = "133",
		name = "vcxproj.filters",
	},
	["v"] = {
		icon = "",
		color = "#009ce5",
		cterm_color = "38",
		name = "v",
	},
	["vscodeignore"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "vscodeignore",
	},
	["vsixmanifest"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "vsixmanifest",
	},
	["vsix"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "vsix",
	},
	["code-workplace"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "code-workplace",
	},
	["code-workspace"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "code-workspace",
	},
	["code-profile"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "code-profile",
	},
	["code-snippets"] = {
		icon = "󰨞",
		color = "#2296f3",
		cterm_color = "33",
		name = "code-snippets",
	},
	["coarc"] = {
		icon = "󱜿",
		color = "#90a4ae",
		cterm_color = "245",
		name = "coarc",
	},
	["coafile"] = {
		icon = "󱜿",
		color = "#90a4ae",
		cterm_color = "245",
		name = "coafile",
	},
	["vue"] = {
		icon = "",
		color = "#40b883",
		cterm_color = "72",
		name = "vue",
	},
	["wat"] = {
		icon = "",
		color = "#7d4dff",
		cterm_color = "99",
		name = "wat",
	},
	["wasm"] = {
		icon = "",
		color = "#7d4dff",
		cterm_color = "99",
		name = "wasm",
	},
	["windi"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "windi",
	},
	["doc"] = {
		icon = "󰈬",
		color = "#0188d1",
		cterm_color = "32",
		name = "doc",
	},
	["docx"] = {
		icon = "󰈬",
		color = "#0188d1",
		cterm_color = "32",
		name = "docx",
	},
	["rtf"] = {
		icon = "󰈬",
		color = "#0188d1",
		cterm_color = "32",
		name = "rtf",
	},
	["odt"] = {
		icon = "󰈬",
		color = "#0188d1",
		cterm_color = "32",
		name = "odt",
	},
	["xaml"] = {
		icon = "󰙳",
		color = "#42a5f5",
		cterm_color = "75",
		name = "xaml",
	},
	["xml"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xml",
	},
	["plist"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "plist",
	},
	["xsd"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xsd",
	},
	["dtd"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "dtd",
	},
	["xsl"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xsl",
	},
	["xslt"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xslt",
	},
	["resx"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "resx",
	},
	["iml"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "iml",
	},
	["xquery"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xquery",
	},
	["tmLanguage"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "tmLanguage",
	},
	["manifest"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "manifest",
	},
	["project"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "project",
	},
	["xml.dist"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xml.dist",
	},
	["xml.dist.sample"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "xml.dist.sample",
	},
	["dmn"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "dmn",
	},
	["jrxml"] = {
		icon = "󰈮",
		color = "#8bc34a",
		cterm_color = "113",
		name = "jrxml",
	},
	["yml.dist"] = {
		icon = "󰈙",
		color = "#ff5252",
		cterm_color = "203",
		name = "yml.dist",
	},
	["yaml.dist"] = {
		icon = "󰈙",
		color = "#ff5252",
		cterm_color = "203",
		name = "yaml.dist",
	},
	["YAML-tmLanguage"] = {
		icon = "󰈙",
		color = "#ff5252",
		cterm_color = "203",
		name = "YAML-tmLanguage",
	},
	["yang"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "yang",
	},
	["zig"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "zig",
	},
	["zon"] = {
		icon = "",
		color = "#faa825",
		cterm_color = "214",
		name = "zon",
	},
	["zip"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "zip",
	},
	["tar"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "tar",
	},
	["gz"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "gz",
	},
	["xz"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "xz",
	},
	["lzma"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "lzma",
	},
	["lz4"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "lz4",
	},
	["br"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "br",
	},
	["bz2"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "bz2",
	},
	["bzip2"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "bzip2",
	},
	["gzip"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "gzip",
	},
	["brotli"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "brotli",
	},
	["7z"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "7z",
	},
	["rar"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "rar",
	},
	["tz"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "tz",
	},
	["txz"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "txz",
	},
	["tgz"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "tgz",
	},
	["zst"] = {
		icon = "󰗄",
		color = "#afb42b",
		cterm_color = "142",
		name = "zst",
	},
	-- Other
	["accdt"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accdt",
	},
	["accda"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accda",
	},
	["accdc"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accdc",
	},
	["accde"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accde",
	},
	["accdp"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accdp",
	},
	["accdr"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accdr",
	},
	["accdu"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "accdu",
	},
	["ade"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "ade",
	},
	["adp"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "adp",
	},
	["laccdb"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "laccdb",
	},
	["ldb"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "ldb",
	},
	["mam"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "mam",
	},
	["maq"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "maq",
	},
	["mdw"] = {
		icon = "󱎎",
		color = "#a22936",
		cterm_color = "125",
		name = "mdw",
	},
	["age"] = {
		icon = "",
		color = "#fed836",
		cterm_color = "221",
		name = "age",
	},
	["bats"] = {
		icon = "󰭟",
		color = "#d2d2d2",
		cterm_color = "252",
		name = "bats",
	},
	["deb"] = {
		icon = "",
		color = "#d80651",
		cterm_color = "161",
		name = "deb",
	},
	["diff"] = {
		icon = "",
		color = "#42a5f5",
		cterm_color = "75",
		name = "diff",
	},
	["django-html"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "django-html",
	},
	["django-txt"] = {
		icon = "",
		color = "#44a047",
		cterm_color = "71",
		name = "django-txt",
	},
	["el"] = {
		icon = "",
		color = "#805eb7",
		cterm_color = "97",
		name = "el",
	},
	["elc"] = {
		icon = "",
		color = "#805eb7",
		cterm_color = "97",
		name = "elc",
	},
	["html"] = {
		icon = "",
		color = "#e44e27",
		cterm_color = "166",
		name = "html",
	},
	["js"] = {
		icon = "󰌞",
		color = "#ffca29",
		cterm_color = "220",
		name = "js",
	},
	["php"] = {
		icon = "󰌟",
		color = "#2088e5",
		cterm_color = "32",
		name = "php",
	},
	["puppet"] = {
		icon = "",
		color = "#fbc02d",
		cterm_color = "214",
		name = "puppet",
	},
	["qml"] = {
		icon = "",
		color = "#42cd52",
		cterm_color = "77",
		name = "qml",
	},
	["reason"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "reason",
	},
	["reason_lisp"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "reason_lisp",
	},
	["ts"] = {
		icon = "󰛦",
		color = "#0188d1",
		cterm_color = "32",
		name = "ts",
	},
	["typ"] = {
		icon = "",
		color = "#0397a7",
		cterm_color = "39",
		name = "typ",
	},
	["uproject"] = {
		icon = "󰦱",
		color = "#ffffff",
		cterm_color = "231",
		name = "uproject",
	},
	["modulemap"] = {
		icon = "",
		color = "#8bc34a",
		cterm_color = "113",
		name = "modulemap",
	},
	["yml"] = {
		icon = "󰈙",
		color = "#ff5252",
		cterm_color = "203",
		name = "yaml",
	},
	["yaml"] = {
		icon = "󰈙",
		color = "#ff5252",
		cterm_color = "203",
		name = "yaml",
	},
	["bbx"] = {
		icon = "",
		color = "#f54436",
		cterm_color = "203",
		name = "bbx",
	},
}
